### ISSUE TITLE
NPE crash when removing filter

### ISSUE THREAD

**Issue by piotrpo** [davideas/FlexibleAdapter#103]
When using AbstractExpandableItem with not initialized sub item list, after setting empty filter and call adapter.filterItems() we have got this crash.

I had work around it setting empty list of subitems after creating expandable item.

 Process: ****, PID: 25237
                                                                  java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                      at eu.davidea.flexibleadapter.FlexibleAdapter.resetFilterFlags(FlexibleAdapter.java:2854)
                                                                      at eu.davidea.flexibleadapter.FlexibleAdapter.filterItems(FlexibleAdapter.java:2453)

**Comment by davideas** [comment]
@piotrpo, thanks, I'm going to fix it soon.
