### ISSUE TITLE
Documentation or implementation bug. Custom ViewHolder cannot be cast to eu.davidea.viewholders.FlexibleViewHolder

### ISSUE THREAD

**Issue by ivankarpey** [davideas/FlexibleAdapter#117]
Issue is correct for the current snapshot.

I'm dealing with sticky headers. Nowhere in docs mentioned, that instead of custom `ViewHolder` inheritance there should be `FlexibleViewHolder` used. And generic constraints of interfaces of provided abstract classes, like `AbstractHeaderItem` and `AbstractSectionableItem` expect to get classes inherited from `RecyclerView.ViewHolder`

However `StickyHeaderHelper` class's method `getHeaderViewHolder(int position)` have direct casting to FlexibleViewHeader and of course will failed if there is simple ViewHolders used with error similar to this one: 

```
FATAL EXCEPTION: main
Process: test, PID: 29504
java.lang.ClassCastException: Fragments.HeaderViewHolder cannot be cast to eu.davidea.viewholders.FlexibleViewHolder
at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.getHeaderViewHolder(StickyHeaderHelper.java:266)
at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.updateHeader(StickyHeaderHelper.java:153)
at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.updateOrClearHeader(StickyHeaderHelper.java:143)
at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.initStickyHeadersHolder(StickyHeaderHelper.java:122)
at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.access$000(StickyHeaderHelper.java:40)
at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper$1.run(StickyHeaderHelper.java:80)
at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
 at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
So i think either it's need to fix docs and probably introduce new abstractions which will be statically checking correct typing, or fix the code to not assume it's use FlexibleViewHolder items.

**Comment by davideas** [comment]
Hello @ivankarpey, thank you for your message.
Indeed that is still not ok, I introduced this constraint as temporary fix for crashing bugs since 2-3 snapshots ago, to allow people continue to develop. Before next beta7, I have to find a final solution, that is good for everybody. I cannot put this in documentation because it is not closed yet.

However, thank you that you have spotted this, I'm going to fix this.

For documentation, the wiki page _Headers and Sections_ clearly explain that sections are identified by `IHeader` and `ISectionable` interfaces.
New and netter docs will follow.

**Comment by davideas** [comment]
@ivankarpey, I refactored the item interfaces signatures to be compliant with StickyHeaderHelper.

**Comment by ivankarpey** [comment]
Thanks. Looks like docs much clearer now. I'm plan to use flexible adapter pretty aggressively in my app and will try to provide some more improvements if will find any.

**Comment by jinsen47** [comment]
Got same exception when my header class extends AbstractHeaderItem and normal item extends AbstractSectionableItem. HELP IN NEED.
I do as the doc said, but still got a ClassCastException, with 5.0.0-b7

**Comment by davideas** [comment]
@jinsen47, can you check if `getLayout()` of both classes returns a different layout?
If not resolved, can you paste here the 2 items and the stacktrace you get?
