### ISSUE TITLE
StackOverflowError when use adapter.setDisplayHeadersAtStartUp(true) or adapter.showAllHeaders();

### ISSUE THREAD

**Issue by 54binge** [davideas/FlexibleAdapter#122]
hi@davideas ,so sorry to disturb you,i try to make a sticky grid header,it can show items well when without adapter.setDisplayHeadersAtStartUp(true) or adapter.showAllHeaders(), but if i set one, it crashed,  Caused by: java.lang.StackOverflowError: stack size 8MB
at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6335)

here is my code, wish you'r help

public class TestActivity2 extends BaseActivity {
    private static final String TAG = "TestActivity2";

    HashMap<String, HeaderItem> headerMap = new HashMap<>();

    private List<GridItem> dataList = new ArrayList<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_test2);

        RecyclerView rcv = (RecyclerView) findViewById(R.id.rcv);
        rcv.setLayoutManager(new StaggeredGridLayoutManager(4, StaggeredGridLayoutManager.VERTICAL));

        getLocalData();

        FlexibleAdapter adapter = new FlexibleAdapter(dataList);
        rcv.setAdapter(adapter);
        rcv.addItemDecoration(new DividerItemDecoration(this, R.drawable.horizontal_line));
        adapter.setDisplayHeadersAtStartUp(true);
        adapter.showAllHeaders();
        adapter.enableStickyHeaders();
    }

    private void getLocalData() {
        AlbumUtil albumUtil = new AlbumUtil(this);
        ArrayList<AlbumFile> list = albumUtil.getLocalAlbumFiles();
        Collections.sort(list);

        for (AlbumFile albumFile : list) {
            if (headerMap.containsKey(albumFile.dayDate)) {
                HeaderItem headerItem = headerMap.get(albumFile.dayDate);
                GridItem gridItem = new GridItem(albumFile, headerItem);

                dataList.add(gridItem);
            } else {
                HeaderItem headerItem = new HeaderItem(albumFile.dayDate, false);
                headerMap.put(albumFile.dayDate, headerItem);

                GridItem gridItem = new GridItem(albumFile, headerItem);

                dataList.add(gridItem);
            }
        }
    }

    class HeaderItem extends AbstractFlexibleItem<HeaderItem.HeaderViewHolder> implements IHeader<HeaderItem.HeaderViewHolder> {
        String title;
        boolean isShowSelect;

        public HeaderItem(String title, boolean isShowSelect) {
            this.title = title;
            this.isShowSelect = isShowSelect;
        }

        public String getTitle() {
            return title;
        }

        public void setTitle(String title) {
            this.title = title;
        }

        public boolean isShowSelect() {
            return isShowSelect;
        }

        public void setShowSelect(boolean showSelect) {
            isShowSelect = showSelect;
        }

        @Override
        public boolean equals(Object inObject) {
            if (inObject instanceof HeaderItem) {
                HeaderItem inItem = (HeaderItem) inObject;
                return this.getTitle().equals(inItem.getTitle());
            }
            return false;
        }

        @Override
        public int getLayoutRes() {
            return R.layout.album_sticky_date_header;
        }

        @Override
        public HeaderViewHolder createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater, ViewGroup parent) {
            return new HeaderViewHolder(inflater.inflate(getLayoutRes(), parent, false), adapter);
        }

        @Override
        public void bindViewHolder(FlexibleAdapter adapter, HeaderViewHolder holder, int position, List payloads) {
            if (payloads.size() > 0) {

            } else {
                holder.dateTV.setText(title);
            }
        }

        class HeaderViewHolder extends FlexibleViewHolder {
            TextView dateTV;
            TextView selectTV;

            public HeaderViewHolder(View view, FlexibleAdapter adapter) {
                super(view, adapter);
                dateTV = (TextView) view.findViewById(R.id.date_tv);
                selectTV = (TextView) view.findViewById(R.id.select_all_tv);
                selectTV.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        v.setSelected(!v.isSelected());
                        showShortMessage(v.isSelected() ? "selectAll" : "unselectAll");
                    }
                });
            }
        }
    }

    private class GridItem extends AbstractFlexibleItem<GridItem.GridViewHolder> implements ISectionable<GridItem.GridViewHolder, HeaderItem> {

        private AlbumFile albumFile;
        private HeaderItem headerItem;

        public GridItem(AlbumFile albumFile, HeaderItem headerItem) {
            this.albumFile = albumFile;
            this.headerItem = headerItem;
        }

        public AlbumFile getAlbumFile() {
            return albumFile;
        }

        public void setAlbumFile(AlbumFile albumFile) {
            this.albumFile = albumFile;
        }

        @Override
        public boolean equals(Object inObject) {
            if (inObject instanceof GridItem) {
                GridItem inItem = (GridItem) inObject;
                return getAlbumFile() == inItem.getAlbumFile();
            }
            return false;
        }

        @Override
        public int getLayoutRes() {
            return R.layout.album_grid_item;
        }

        @Override
        public GridViewHolder createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater, ViewGroup parent) {
            return new GridViewHolder(inflater.inflate(getLayoutRes(), parent, false), adapter);
        }

        @Override
        public void bindViewHolder(FlexibleAdapter adapter, GridViewHolder holder, int position, List payloads) {
            AlbumItem albumItem = (AlbumItem) holder.itemView;
            albumItem.setAlbumFile(getAlbumFile());
        }

        @Override
        public HeaderItem getHeader() {
            return headerItem;
        }

        @Override
        public void setHeader(HeaderItem header) {
            this.headerItem = header;
        }

        public class GridViewHolder extends FlexibleViewHolder {

            public GridViewHolder(View view, FlexibleAdapter adapter) {
                super(view, adapter);

            }
        }
    }

}

**Comment by davideas** [comment]
Hi @54binge, you don't have to call `showAllHeaders()` because that method is already called in `setDisplayHeadersAtStartUp()`.

Also for the HeaderViewHolder, you need to pass true to the super constructor, to avoid some crashing issues when you will scroll.

**Comment by 54binge** [comment]
Hi @davideas ,thanks for your reply.
In fact, the application crashed immediately when setDisplayHeadersAtStartUp() is called,there is nothing to do with the scrolling.
And I can't find where to pass "true" in the HeaderViewHolder constructor.
looking forward to your next reply!

**Comment by davideas** [comment]
@54binge, indeed scrolling is a different thing, but if you don't find the new parameter means that you are using an old version, please use beta7, and you actually need it.
(I've updated a little the Wiki for beta7).

Regarding the main problem, I think it's the double call, but I need to check better, in the meantime, please remove `showAllHeaders()`.

**Comment by davideas** [comment]
Another important thing, you have to provide a copy of dataList. At the moment that is necessary.

**Comment by davideas** [comment]
@54binge, I've tried your code, I removed the creation of `dataList` because I don't have the objects. But I used my own list and everything works fine, just the header is duplicated because duplicated is the call...
Can you please enable logs and paste them here, and also can you try to run it debug mode?

**Comment by 54binge** [comment]
@davideas 
it works fine use handler,i need research it more.
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_test2);

        RecyclerView rcv = (RecyclerView) findViewById(R.id.rcv);
        rcv.setLayoutManager(new StaggeredGridLayoutManager(4, StaggeredGridLayoutManager.VERTICAL));

        getLocalData();

        final FlexibleAdapter adapter = new FlexibleAdapter(dataList);
        rcv.setAdapter(adapter);
        rcv.addItemDecoration(new DividerItemDecoration(this, R.drawable.horizontal_line));
        baseHandler.post(new Runnable() {
            @Override
            public void run() {
                adapter.showAllHeaders();
            }
        });

        adapter.enableStickyHeaders();


    }

**Comment by davideas** [comment]
Well, it is a workaround, it would be interesting to see your logs, maybe there's a problem somewhere else.

**Comment by 54binge** [comment]
@davideas 
there is logs,i don't use handler it still crash

06-25 14:13:45.283 7711-7711/com.example E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
06-25 14:13:45.296 7711-7711/com.example E/AndroidRuntime: Error reporting WTF
                                        android.os.TransactionTooLargeException
                                            at android.os.BinderProxy.transactNative(Native Method)
                                            at android.os.BinderProxy.transact(Binder.java:504)
                                            at android.app.ActivityManagerProxy.handleApplicationWtf(ActivityManagerNative.java:4310)
                                            at com.android.internal.os.RuntimeInit.wtf(RuntimeInit.java:344)
                                            at android.util.Log$1.onTerribleFailure(Log.java:104)
                                            at android.util.Log.wtf(Log.java:294)
                                            at android.util.Log.wtf(Log.java:275)
                                            at com.mob.tools.log.MobUncaughtExceptionHandler.uncaughtException(Unknown Source)
                                            at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                            at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
06-25 14:13:45.511 7711-7733/com.example I/art: Background partial concurrent mark sweep GC freed 82701(6MB) AllocSpace objects, 16(46MB) LOS objects, 5% free, 74MB/78MB, paused 1.591ms total 213.745ms
06-25 14:13:45.511 7711-7711/com.example I/art: WaitForGcToComplete blocked for 53.259ms for cause Alloc
06-25 14:13:45.694 7711-7728/com.example W/art: Suspending all threads took: 48.071ms
06-25 14:13:45.704 7711-7733/com.example W/art: Suspending all threads took: 9.962ms
06-25 14:13:45.722 7711-7733/com.example I/art: Background partial concurrent mark sweep GC freed 59992(4MB) AllocSpace objects, 2(4MB) LOS objects, 4% free, 85MB/89MB, paused 11.469ms total 177.634ms
06-25 14:13:45.988 7711-7733/com.example I/art: Background partial concurrent mark sweep GC freed 73002(5MB) AllocSpace objects, 2(15MB) LOS objects, 3% free, 96MB/100MB, paused 1.371ms total 163.060ms
06-25 14:13:45.988 7711-7711/com.example I/art: WaitForGcToComplete blocked for 37.299ms for cause Alloc
06-25 14:13:46.103 7711-7711/com.example E/AndroidRuntime: Original WTF:
                                        android.util.Log$TerribleFailure: stack size 8MB
                                            at android.util.Log.wtf(Log.java:291)
                                            at android.util.Log.wtf(Log.java:275)
                                            at com.mob.tools.log.MobUncaughtExceptionHandler.uncaughtException(Unknown Source)
                                            at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                            at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                         Caused by: java.lang.StackOverflowError: stack size 8MB
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6335)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                            at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6336)
                                        	at android.view.ViewGroup.
06-25 14:13:46.255 7711-7728/com.example W/art: Suspending all threads took: 108.457ms
06-25 14:13:46.265 7711-7733/com.example W/art: Suspending all threads took: 10.055ms
06-25 14:13:46.285 7711-7733/com.example I/art: Background partial concurrent mark sweep GC freed 16605(1330KB) AllocSpace objects, 15(66MB) LOS objects, 7% free, 49MB/53MB, paused 11.360ms total 168.989ms
06-25 14:13:46.555 7711-7733/com.example I/art: Background partial concurrent mark sweep GC freed 78396(5MB) AllocSpace objects, 3(10MB) LOS objects, 6% free, 58MB/62MB, paused 1.562ms total 160.541ms
06-25 14:13:46.555 7711-7732/com.example I/art: WaitForGcToComplete blocked for 111.069ms for cause HeapTrim
06-25 14:13:46.660 7711-7728/com.example W/art: Suspending all threads took: 12.462ms
06-25 14:13:46.670 7711-7733/com.example W/art: Suspending all threads took: 9.850ms
06-25 14:13:46.679 7711-7733/com.example I/art: Background sticky concurrent mark sweep GC freed 56102(4MB) AllocSpace objects, 0(0B) LOS objects, 0% free, 72MB/72MB, paused 11.124ms total 38.032ms
06-25 14:13:46.855 7711-7711/com.example E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
06-25 14:13:46.859 7711-7733/com.example I/art: Background partial concurrent mark sweep GC freed 66782(5MB) AllocSpace objects, 2(13MB) LOS objects, 4% free, 84MB/88MB, paused 1.981ms total 169.145ms
06-25 14:13:47.163 7711-7733/com.example I/art: Background partial concurrent mark sweep GC freed 149207(9MB) AllocSpace objects, 5(31MB) LOS objects, 5% free, 70MB/74MB, paused 5.763ms total 195.674ms
06-25 14:13:47.383 7711-7733/com.example I/art: Background partial concurrent mark sweep GC freed 147382(9MB) AllocSpace objects, 2(5MB) LOS objects, 4% free, 79MB/83MB, paused 1.361ms total 182.026ms
06-25 14:13:47.630 7711-7807/com.example I/Process: Sending signal. PID: 7711 SIG: 9

**Comment by davideas** [comment]
@54binge, ok I've seen the logs and deleted the message, not useful.
I need that you enable the logs of the Adapter and send that to me. Also put some logs in the various methods of your Activity so I can know in which point the execution is.
Thanks.

**Comment by 54binge** [comment]
@davideas 
when i see the logs,i also think it not useful,even if i call FlexibleAdapter.enableLogs(true);
just now, i put the method setAdapter() after method adapter.setDisplayHeadersAtStartUp(true),
all become normal and works very well.
thank you for these days!

**Comment by davideas** [comment]
Cool, so the problem is the order of the set?
I wonder why the demo App doesn't crash too, can you put here the logs of when it crash?
Because I've rewriting the Wiki pages just now and I need to be sure that the call `setDisplayHeadersAtStartUp()` can be after or must be before setting the Adapter to the RV.
Thanks.

**Comment by 54binge** [comment]
I pasted all logs when it crashed,when it became normal,i tried the order of method `setDisplayHeadersAtStartUp(true)`,in fact,it is not the reason,i think it is better to  call it after `setAdapter()`,maybe it is the time to restart android studio or reboot my computer :)

**Comment by davideas** [comment]
I understood that could be something related with the setContentView and view hierarchy even before the Adapter since you don't see any logs from it when you enableLogs().
