### ISSUE TITLE
onLoadMore is not called when binding items with METHOD B

### ISSUE THREAD

**Issue by 54binge** [davideas/FlexibleAdapter#130]
hi @davideas 
i do it step by step as below,but the method onLoadMore not be called
eu.davidea:flexible-adapter:5.0.0-b7
implements FlexibleAdapter.EndlessScrollListener,
mRecyclerView.setLayoutManager(createNewGridLayoutManager()),
mAdapter.setEndlessScrollListener(this, new LoadMoreItem());
mAdapter.setEndlessScrollThreshold(1);

is there something wrong with me?

**Comment by davideas** [comment]
The method of the listener is called based on these conditions:

``` java
if (mEndlessScrollListener != null && getGlobalPositionOf(mProgressItem) < 0
		&& position >= getItemCount() - mEndlessScrollThreshold) {
	if (!mLoading) {
		mLoading = true;
		mRecyclerView.post(new Runnable() {
			@Override
			public void run() {
				mItems.add(mProgressItem);
				notifyItemInserted(getItemCount());
				mEndlessScrollListener.onLoadMore();
			}
		});
	}
}
```
It means that the progress item must not be present in the list and that the ```binding position is >= getItemCount() - mEndlessScrollThreshold```.

**Comment by 54binge** [comment]
@davideas ,hello
if i called super.onBindViewHolder(holder,position,payloads),it crash
07-06 10:47:01.269 19373-19373/com.example.emulator V/FlexibleAdapter: Showing header at position 0 header=com.example.view.HeaderItem@3af59394
07-06 10:47:01.269 19373-19373/com.example.emulator V/FlexibleAdapter: addItem delegates addition to addItems!
07-06 10:47:01.269 19373-19373/com.example.emulator V/FlexibleAdapter: addItems on position=0 itemCount=1
07-06 10:47:01.269 19373-19373/com.example.emulator V/FlexibleAdapter: Showing header at position 6 header=com.example.view.HeaderItem@25ff1e3d
07-06 10:47:01.269 19373-19373/com.example.emulator V/FlexibleAdapter: addItem delegates addition to addItems!
07-06 10:47:01.269 19373-19373/com.example.emulator V/FlexibleAdapter: addItems on position=6 itemCount=1
07-06 10:47:01.269 19373-19373/com.example.emulator V/FlexibleAdapter: Showing header at position 15 header=com.example.view.HeaderItem@904a632
07-06 10:47:01.269 19373-19373/com.example.emulator V/FlexibleAdapter: addItem delegates addition to addItems!
07-06 10:47:01.270 19373-19373/com.example.emulator V/FlexibleAdapter: addItems on position=15 itemCount=1
07-06 10:47:01.270 19373-19373/com.example.emulator V/FlexibleAdapter: Showing header at position 25 header=com.example.view.HeaderItem@3e4a2f83
07-06 10:47:01.270 19373-19373/com.example.emulator V/FlexibleAdapter: addItem delegates addition to addItems!
07-06 10:47:01.270 19373-19373/com.example.emulator V/FlexibleAdapter: addItems on position=25 itemCount=1
07-06 10:47:01.270 19373-19373/com.example.emulator V/FlexibleAdapter: Showing header at position 37 header=com.example.view.HeaderItem@22625500
07-06 10:47:01.270 19373-19373/com.example.emulator V/FlexibleAdapter: addItem delegates addition to addItems!
07-06 10:47:01.270 19373-19373/com.example.emulator V/FlexibleAdapter: addItems on position=37 itemCount=1
07-06 10:47:01.477 19373-19393/com.example.emulator I/art: Background sticky concurrent mark sweep GC freed 25906(1247KB) AllocSpace objects, 1(20KB) LOS objects, 2% free, 52MB/54MB, paused 28.635ms total 82.344ms
07-06 10:47:02.033 19373-19373/com.example.emulator D/AndroidRuntime: Shutting down VM
07-06 10:47:02.500 19373-19387/com.example.emulator W/art: Suspending all threads took: 383.271ms
07-06 10:47:02.508 19373-19393/com.example.emulator W/art: Suspending all threads took: 7.501ms
07-06 10:47:02.536 19373-19393/com.example.emulator I/art: Background sticky concurrent mark sweep GC freed 28434(666KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 78MB/78MB, paused 23.920ms total 502.795ms
07-06 10:47:02.676 19373-19387/com.example.emulator W/art: Suspending all threads took: 57.740ms
07-06 10:47:02.684 19373-19393/com.example.emulator W/art: Suspending all threads took: 7.939ms
07-06 10:47:02.699 19373-19393/com.example.emulator I/art: Background partial concurrent mark sweep GC freed 72581(7MB) AllocSpace objects, 14(4MB) LOS objects, 4% free, 84MB/88MB, paused 9.222ms total 154.718ms
07-06 10:47:02.710 19373-19418/com.example.emulator D/OpenGLRenderer: Flushing caches (mode 0)
07-06 10:47:02.715 19373-19390/com.example.emulator I/System.out: [CDS]close[0]
07-06 10:47:02.715 19373-19390/com.example.emulator I/NetworkManagementSocketTagger: untagSocket(60)
07-06 10:47:02.715 19373-19390/com.example.emulator D/FlymeTrafficTracking: untag(60) com.example.emulator FinalizerDaemon uid 10051 1751ms
07-06 10:47:02.911 19373-19393/com.example.emulator I/art: Background partial concurrent mark sweep GC freed 88911(10MB) AllocSpace objects, 3(8MB) LOS objects, 4% free, 91MB/95MB, paused 1.210ms total 137.365ms
07-06 10:47:03.172 19373-19387/com.example.emulator W/art: Suspending all threads took: 52.594ms
07-06 10:47:03.173 19373-19373/com.example.emulator A/MobUncaughtExceptionHandler: stack size 8MB
                                                                                                   java.lang.StackOverflowError: stack size 8MB
                                                                                                       at android.util.SparseArray.get(SparseArray.java:104)
                                                                                                       at android.content.res.StringBlock.get(StringBlock.java:70)
                                                                                                       at android.content.res.AssetManager.getResourceText(AssetManager.java:162)
                                                                                                       at android.content.res.Resources.getText(Resources.java:332)
                                                                                                       at android.content.res.Resources.getString(Resources.java:434)
                                                                                                       at android.content.Context.getString(Context.java:387)
                                                                                                       at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:112)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                                       at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                                       at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                                       at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                                       at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                                       at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                                       at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                                       at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                                       at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                                       at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                                   	at eu.davidea.flexibleadapter.Fl
07-06 10:47:03.196 19373-19393/com.example.emulator I/art: Background partial concurrent mark sweep GC freed 77106(9MB) AllocSpace objects, 2(15MB) LOS objects, 3% free, 116MB/120MB, paused 1.326ms total 229.487ms
07-06 10:47:03.508 19373-19393/com.example.emulator I/art: Background partial concurrent mark sweep GC freed 98962(11MB) AllocSpace objects, 5(22MB) LOS objects, 3% free, 120MB/124MB, paused 1.274ms total 193.071ms
07-06 10:47:03.781 19373-19373/com.example.emulator D/Error: ERR: exClass=java.lang.StackOverflowError
07-06 10:47:03.781 19373-19373/com.example.emulator D/Error: ERR: exMsg=stack size 8MB
07-06 10:47:03.782 19373-19373/com.example.emulator D/Error: ERR: file=SparseArray.java
07-06 10:47:03.782 19373-19373/com.example.emulator D/Error: ERR: class=android.util.SparseArray
07-06 10:47:03.782 19373-19373/com.example.emulator D/Error: ERR: method=get line=104
07-06 10:47:03.877 19373-19393/com.example.emulator W/art: Suspending all threads took: 69.439ms
07-06 10:47:03.881 19373-19373/com.example.emulator D/Error: ERR: stack=android.util.Log$TerribleFailure: stack size 8MB
                                                                                 at android.util.Log.wtf(Log.java:291)
                                                                                 at android.util.Log.wtf(Log.java:275)
                                                                                 at com.mob.tools.log.MobUncaughtExceptionHandler.uncaughtException(Unknown Source)
                                                                                 at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                 at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                              Caused by: java.lang.StackOverflowError: stack size 8MB
                                                                                 at android.util.SparseArray.get(SparseArray.java:104)
                                                                                 at android.content.res.StringBlock.get(StringBlock.java:70)
                                                                                 at android.content.res.AssetManager.getResourceText(AssetManager.java:162)
                                                                                 at android.content.res.Resources.getText(Resources.java:332)
                                                                                 at android.content.res.Resources.getString(Resources.java:434)
                                                                                 at android.content.Context.getString(Context.java:387)
                                                                                 at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:112)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                 at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                 at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                 at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                 at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                 at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                 at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                 at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                 at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                 at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                             	at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(Flexible
07-06 10:47:03.883 19373-19373/com.example.emulator D/Error: ERR: TOTAL BYTES WRITTEN: 13230932
07-06 10:47:03.884 19373-19373/com.example.emulator E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
07-06 10:47:03.894 19373-19373/com.example.emulator E/AndroidRuntime: Error reporting WTF
                                                                                      android.os.TransactionTooLargeException
                                                                                          at android.os.BinderProxy.transactNative(Native Method)
                                                                                          at android.os.BinderProxy.transact(Binder.java:509)
                                                                                          at android.app.ActivityManagerProxy.handleApplicationWtf(ActivityManagerNative.java:4366)
                                                                                          at com.android.internal.os.RuntimeInit.wtf(RuntimeInit.java:358)
                                                                                          at android.util.Log$1.onTerribleFailure(Log.java:104)
                                                                                          at android.util.Log.wtf(Log.java:294)
                                                                                          at android.util.Log.wtf(Log.java:275)
                                                                                          at com.mob.tools.log.MobUncaughtExceptionHandler.uncaughtException(Unknown Source)
                                                                                          at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                          at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
07-06 10:47:03.897 19373-19393/com.example.emulator I/art: Background partial concurrent mark sweep GC freed 72473(8MB) AllocSpace objects, 3(19MB) LOS objects, 2% free, 140MB/144MB, paused 71.899ms total 229.110ms
07-06 10:47:04.131 19373-19393/com.example.emulator I/art: Background partial concurrent mark sweep GC freed 87836(10MB) AllocSpace objects, 9(49MB) LOS objects, 3% free, 111MB/115MB, paused 1.148ms total 142.486ms
07-06 10:47:04.327 19373-19393/com.example.emulator I/art: Background partial concurrent mark sweep GC freed 87692(10MB) AllocSpace objects, 2(9MB) LOS objects, 3% free, 126MB/130MB, paused 1.168ms total 133.725ms
07-06 10:47:04.400 19373-19393/com.example.emulator W/art: Suspending all threads took: 13.482ms
07-06 10:47:04.496 19373-19373/com.example.emulator E/AndroidRuntime: Original WTF:
                                                                                      android.util.Log$TerribleFailure: stack size 8MB
                                                                                          at android.util.Log.wtf(Log.java:291)
                                                                                          at android.util.Log.wtf(Log.java:275)
                                                                                          at com.mob.tools.log.MobUncaughtExceptionHandler.uncaughtException(Unknown Source)
                                                                                          at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                          at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                                       Caused by: java.lang.StackOverflowError: stack size 8MB
                                                                                          at android.util.SparseArray.get(SparseArray.java:104)
                                                                                          at android.content.res.StringBlock.get(StringBlock.java:70)
                                                                                          at android.content.res.AssetManager.getResourceText(AssetManager.java:162)
                                                                                          at android.content.res.Resources.getText(Resources.java:332)
                                                                                          at android.content.res.Resources.getString(Resources.java:434)
                                                                                          at android.content.Context.getString(Context.java:387)
                                                                                          at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:112)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                          at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                          at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                          at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                          at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                          at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                          at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                          at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1130)
                                                                                          at com.example.adapter.AlbumAdapter.onBindViewHolder(AlbumAdapter.java:135)
                                                                                          at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1103)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                      	at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHol
07-06 10:47:04.632 19373-19387/com.example.emulator W/art: Suspending all threads took: 8.239ms
07-06 10:47:04.639 19373-19393/com.example.emulator I/art: Background partial concurrent mark sweep GC freed 81511(9MB) AllocSpace objects, 16(32MB) LOS objects, 2% free, 130MB/134MB, paused 1.122ms total 206.976ms
07-06 10:47:04.834 19373-19393/com.example.emulator I/art: Background partial concurrent mark sweep GC freed 87931(10MB) AllocSpace objects, 5(54MB) LOS objects, 4% free, 92MB/96MB, paused 1.198ms total 152.791ms
07-06 10:47:05.023 19373-19373/com.example.emulator E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!

**Comment by davideas** [comment]
@54binge, you right, there's a bug for when AutoMap is not active, I'm going to fix it.
Indeed everything works fine using item interfaces, but not when using adapter binding methods.

**Comment by davideas** [comment]
I've changed the signature method onLoadMore from private to protected, so you can call it. Please read the new documentation I've just written for EndlessScroll.

**Comment by 54binge** [comment]
thank you @davideas !
