### ISSUE TITLE
Sticky Headers under scrollable toolbar

### ISSUE THREAD

**Issue by 3v0lution** [davideas/FlexibleAdapter#142]
Fist of all, thanks for this awesome project!

I use FlexibleAdapter with sticky headers.  The toolbar of the app is scrollable (scrollFlag = scroll|enterAlways). The problem is when the app starts, the first sticky header is atop of the first list item (SectionableItem):

![image](https://cloud.githubusercontent.com/assets/11610668/16887728/101955fe-4adc-11e6-84c5-2a3c9f23b624.png)

The problem occurs only if the headers are sticky and as soon you scroll down and up to the top again it works. Then it looks like this:

![image](https://cloud.githubusercontent.com/assets/11610668/16887796/7d049660-4adc-11e6-88fb-2bbaf007cb70.png)

Any suggestions?

**Comment by davideas** [comment]
Thanks for the message @3v0lution, are you using wrap_content and beta7 ? If yes, please use SNAPSHOT since this has been resolved after beta7, already reported in issue 121.
Let me know, if it is not that.
Davide

**Comment by 3v0lution** [comment]
Thanks for the fast reply!

Yes, like you said, I used beta 7. With the snapshot it works at the beginning when the app starts, but as soon as I filter the list and clear the search text (whole list should be shown again) the problem occurs again.
After this, when I do the same thing one more time (search/filter for something and clear the filter afterwards) the headers are duplicated for each section (1. search = 1 header, 2. search = 2 headers, 3. = 3 headers etc.)
(I don't know if it's already reported) 

![image](https://cloud.githubusercontent.com/assets/11610668/16889406/6fb9363c-4ae6-11e6-9363-a56a78532696.png)

**Comment by davideas** [comment]
That's weird, I can't tell about it now, because I have modified a lot of code to improve performance until last snapshot, filter in primis. Strange that, because it sees the header as hidden and so it displays again. Are you changing that parameter?

I just published the newest API so you will be the first to test. To have you now, you need to delete manually the cache in the gradle for my group-id/artifact.
`C:\Users\<user>\.gradle\caches\modules-2\files-2.1\eu.davidea\flexible-adapter`.

**Comment by 3v0lution** [comment]
I deleted the cache and tested the whole thing again, but unfortunately both problems occur again.
I don't set the hidden attribute of the header item as true/false anywhere in my code, so it can't be the reason in my oppinion.

**Comment by davideas** [comment]
The fact that the item appear below, filter and sticky header are not compatible each other's, I disable the sticky when searchText is not empty. So when it is enabled it might be normal to have the header over the item.
For the duplication, can u tell me if the header implements `IFilterable` and what are you searching exactly?

**Comment by 3v0lution** [comment]
Only the SectionableItem inplements IFilterable, the header doesn't. 
In the filter method of the SectionableItem, I'm searching if the searchText matches the title/date and return true or false.

**Comment by davideas** [comment]
Maybe I've found the cause of your first issue, I can fix that, while the duplication probably is due because you are not passing a copy of the list to `filterItems()`.

I debugged and reproduced the duplication as you showed, so this is not a bug: you basically have to pass a copy of the original list because the filter removes the items from that list, and every time the searchText is reduced in length it must take items from the bigger set, to include a larger subset of filtered items. Therefore it's mandatory the copy for this simple reason.
At the end of the process when searchText is empty, the filter is expecting an original copy without headers and it provides to restore the previous state assuring the headers are displayed as before.

Why I don't keep the original list? Simple, that list already exists in the user code and there's no need to duplicate it in memory.

**Comment by 3v0lution** [comment]
Everytime the searchtext changes, I call `filterItems(copyOriginalItems)` while the list copyOriginalItems contains only SectionableItems. Each SectionableItem has a header assigned.
So I don't see anything wrong in my code (if I get you right).

`private List<IFlexible> originalItems;`

`originalItems = AdapterData.getRfrdList();`
`mAdapter = new FlexibleAdapter<>(originalItems);`

`@Override`
    `public boolean onQueryTextChange(String query) {`
        `List< IFlexible > copyOriginalItems = originalItems;`

        mAdapter.setSearchText(query);
        mAdapter.filterItems(copyOriginalItems);
        mAdapter.notifyDataSetChanged();

        return true;
    }

**Comment by davideas** [comment]
@3v0lution This is a copy:
``` java
List<IFlexible> copyOriginalItems = new ArrayList<>(originalItems);
```

Your assignment just give the original reference to copyOriginalItems.

**Comment by 3v0lution** [comment]
Oops, yes of course :)
Now it adds only a second header to every section when I clear the filter.

**Comment by davideas** [comment]
Be sure your list doesn't have headers. That's is not possible.

**Comment by 3v0lution** [comment]
Well, the list contains only SectionableItems. Each SectionableItem has a header assigned.
This should be correct, or am I wrong?

**Comment by davideas** [comment]
So your list seems ok.
I've generated a new Snapshot, with the fix of item under sticky header at start up and after updateDataSet. Clean again the cache and recompile.

Regarding the duplication of headers when filter is cleared out, I don't know have enough elements now to understand why in your code doesn't work, in the demo app it is working.

**Comment by davideas** [comment]
Ahh, don't call `notifyDataSetChanged()`, and in general don't, until it is strictly necessary. Anyway, the adapter can be configured in the way it can be called when it is necessary. In the last improvements for performance i tuned the changes in the way that method is now called in a special case.
I will have to add this in the documentation, since it is quite important now.

`notifyDataSetChanged()` force the LayoutManager and RecyclerView to rebind all the items without any kind of animation, indeed it is instantaneous, but no effects.
Not last, all notifyXXX() methods are in general handled by the adapter too.

**Comment by 3v0lution** [comment]
Thanks for the tip! I don't call `notifyDataSetChanged()` anymore but the problem was something different. While debugging I saw that the method `mAdapter.setDisplayHeadersAtStartUp(true);` creates header items in the list. I didn't thought about it first because I passed a list with just SectionableItems :/

The bug with the item under sticky header is still there as soon as I clear the searchtext. Everywhere else it works fine now (even when the list is filtered).

**Comment by davideas** [comment]
So you were calling `setDisplayHeadersAtStartUp()` and `showAllHeaders()` subsequently? uhm...

The item under sticky header after the searchText is cleared out, now it depends, if the first item was in the result, then that item is not anymore below the sticky header item; if the first item was _not_ the first result, then it's normal to have the sticky header appearing on the top, for the reason i explained you some message ago.

Is now everything ok?

**Comment by 3v0lution** [comment]
I just call setDisplayHeadersAtStartUp() without showAllHeaders()

Sticky Headers: 
In this case, it works fine now.

Thanks for support

**Comment by 3v0lution** [comment]
I just call `setDisplayHeadersAtStartUp()` without `showAllHeaders()`

Sticky Headers:
In this case, it works fine now

**Comment by davideas** [comment]
Glad to have helped you and also thank you to have spotted this bug.
Please, follow the library for when the final release will be published, still 2-3 of months...

**Comment by 3v0lution** [comment]
Did you change something in relation to the sticky headers? (I use the snapshot)
The headers can't be set as sticky anymore (works with the latest beta) and if the searchtext is cleared after filtering the first header is now under the toolbar and if you want to filter again the app crashes with IndexOutOfBoundsException.

**Comment by davideas** [comment]
Only for the issue 139.
Exception where?

**Comment by 3v0lution** [comment]
`java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{6f53bda position=170 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}
                                                                               at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4801)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4932)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                                               at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                               at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                               at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3211)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3067)
                                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:120)
                                                                               at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                               at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1319)
                                                                               at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:815)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                               at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                           	at android.view.Choreographer.doCallbacks(Choreograph`

**Comment by davideas** [comment]
That is caused by Inconsistency between LayoutManager and Adapter positions, maybe the fix I've done, a simple `scrollToPosition()` in post for the object RecyclerView should be delayed a bit.

But you have to tell me, the exact steps to reproduce it, or you can modify this behavior creating your library with this fix. Your layout is very different from the demoApp since you have collapsible toolbar you said, that could also be a cause, I don't man, we need to investigate.

1. try to make it happen systematically
2. and try to change something for your layout and see if it works then.
3, I can try to add a delay of few ms.

Davide

**Comment by 3v0lution** [comment]
Ok, I will try.
Do you have an idea why the headers can't be made sticky anymore?

**Comment by davideas** [comment]
Nothing else is changed, maybe are you using multiple instances of Adapters and Model objects?
