### ISSUE TITLE
android:theme tag is not allowed in layout file.

### ISSUE THREAD

**Issue by Dharmaraj** [davideas/FlexibleAdapter#161]
-> I integrated FlexibleAdapter library for Sticky List in my project. And I have to define android:theme tag on my layout. But when I added android:theme tag, my project is crash because of sticky header enabled.  I can create the header with section view. But when I will enable sticky header using  "adapter.enableStickyHeaders();". Then App will be crashed. 
Actual behavior : App crash when call ,  "adapter.enableStickyHeaders();". If I have android:theme tag in layout file.
Expected behavior: App shouldn't crash. App should support the android:theme tag in layout file.

**Example design xml:** 
_**my_view.xml**_
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:theme="@style/mytheme"> -- will crash when i will add theme tag here.

    <android.support.v7.widget.RecyclerView
        android:id="@+id/myRecyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    
    <include layout="@layout/sticky_header_layout" />
</RelativeLayout>

**Coding:**
 "adapter.enableStickyHeaders();" will crash when I will call this.

**Error O/P**
FATAL EXCEPTION: main
Process: stickyrecyvlerviewlistexample, PID: 32355
java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
at eu.davidea.flexibleadapter.FlexibleAdapter.getStickySectionHeadersHolder(FlexibleAdapter.java:975)
at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.initStickyHeadersHolder(StickyHeaderHelper.java:113)
at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.access$000(StickyHeaderHelper.java:41)
at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper$1.run(StickyHeaderHelper.java:79)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6873)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by davideas** [comment]
@Dharmaraj, I've made the fix, but still not committed.
Please monitor the resolution of this issue for when it will be available.

**Comment by Dharmaraj** [comment]
Sure. Thanks! @davideas .
