### ISSUE TITLE
[Developer version] Crash when touch Recyclerview

### ISSUE THREAD

**Issue by mdtuyen** [davideas/FlexibleAdapter#167]
FATAL EXCEPTION: main
                                                                          Process: com.gchat.messenger.beta, PID: 10293
                                                                          java.lang.IllegalStateException: Layout state should be one of 100 but it is 10
                                                                              at android.support.v7.widget.RecyclerView$State.assertLayoutStep(RecyclerView.java:10477)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3277)
                                                                              at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3080)
                                                                              at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1478)
                                                                              at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1542)
                                                                              at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2649)
                                                                              at android.view.View.dispatchTouchEvent(View.java:8975)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2698)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2410)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2559)
                                                                              at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1767)
                                                                              at android.app.Activity.dispatchTouchEvent(Activity.java:2866)
                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2520)
                                                                              at com.android.internal.policy.impl.MultiPhoneWindow$MultiPhoneDecorView.dispatchTouchEvent(MultiPhoneWindow.java:537)
                                                                              at android.view.View.dispatchPointerEvent(View.java:9180)
                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4708)
                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4546)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4074)
                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4127)
                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4093)
                                                                              at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4203)
                                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4101)
                                                                          	at android.view.ViewRootImpl$AsyncInputStage.apply(V

**Comment by davideas** [comment]
I don't know man, try to downgrade or upgrade Support Library.
Please don't open issue not related to this library, thanks.

**Comment by mdtuyen** [comment]
Sorry, I don't know why but when I connect your project to new my project the error occur (old project work fine). The bug have been resolve by remove  attribute primaryTextSelector (<attr name="primaryTextSelector" format="reference" />) . I have no time to check more.

I have a question that: I use endless feature for your library with header. Here is my code:

```
 public void onLoadMore() {
        if (mAdapter.hasSearchText()) {
            mAdapter.onLoadMoreComplete(null);
            return;
        }
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                final List<AbstractFlexibleItem> newItems = new ArrayList<>(2);
                int count = new Random().nextInt(7);
                int totalItemsOfType = mAdapter.getItemCountOfTypes(R.layout.recycler_expandable_item);
                HeaderItem item = (HeaderItem) DatabaseService.getInstance().getDatabaseList().get(DatabaseService.getInstance().getDatabaseList().size() - 1);
                for (int i = 1; i <= count; i++) {
                    newItems.add(DatabaseService.newSimpleItem(totalItemsOfType + i, item));
                }
                mAdapter.onLoadMoreComplete(newItems);
                String message = (newItems.size() > 0 ?
                        "Simulated: " + newItems.size() + " new items arrived :-)" :
                        "Simulated: No more items to load :-(");
                Toast.makeText(ApplicationLoader.applicationContext, message, Toast.LENGTH_SHORT).show();
            }
        }, 3000);
    }

```

The new I tem added to the header but when I collape header it not collape the new item added.

**Comment by davideas** [comment]
@mdtuyen, I suspect that HeaderItem it's not expandable. As you see from my code I create newExpandableItem with subItems already inside. And only the main item is added to the list. You forgot?

**Comment by mdtuyen** [comment]
I have two type item: headeritem with expandable feature, and simple item. I want make a recyclerview with sticky header, endless, expandable and have some fix item header at top.

**Comment by davideas** [comment]
So you need a `AbstractExpandableHeaderItem` and a `SubItem` of type `AbstractFlexibleItem`.
In the `onLoadMore()` you create `AbstractExpandableHeaderItem` with the sub items inside and add the main item to the Adapter list `onLoadMoreComplete(newItems)`.

For the fixed header you can name it as you want, I will call here `FixedTopHeaderItem` of type `AbstractFlexibleItem`. Then you add it _only_ to the top of the Adapter list (not to the database!) every time you create the list or clear the search text -> `addItem(0, fixedTopHeaderItem)`;

Read carefully my comments of the methods and the Wiki pages.

**Comment by davideas** [comment]
@mdtuyen, please be aware that, Endless Scrolling is going to be changed very soon. In order to support the new features and a better logic, the behaviors and callbacks methods will be refactored.

Please check issue #233 for the latest developments.
