### ISSUE TITLE
java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.support.v7.widget.RecyclerView$LayoutParams on Nexus 6p

### ISSUE THREAD

**Issue by jonathanyee** [davideas/FlexibleAdapter#199]
```
java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.support.v7.widget.RecyclerView$LayoutParams
       at android.support.v7.widget.RecyclerView.getChildViewHolderInt(RecyclerView.java:3979)
       at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfoForItem(RecyclerView.java:8795)
       at android.support.v7.widget.RecyclerViewAccessibilityDelegate$1.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:90)
       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:246)
       at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompatJellyBean.java:61)
       at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6538)
       at android.view.View.createAccessibilityNodeInfoInternal(View.java:6499)
       at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:23471)
       at android.view.View.createAccessibilityNodeInfo(View.java:6482)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1020)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:844)
       at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:156)
       at android.view.AccessibilityInteractionController.-wrap1(AccessibilityInteractionController.java)
       at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1198)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

Doing an internal test in my company and sticky headers is only crashing on this phone for some reason while scrolling.
API Level 24
Nexus 6p running on android 7.0

Turning off sticky headers and not calling setDisplayHeadersAtStartup did not cause the app to crash

heres relevant code:
```
recyclerView = (RecyclerView) getView().findViewById(R.id.list);
recyclerView.addItemDecoration(new ConnectionDividerDecoration(getContext(), 5));
recyclerView.setLayoutManager(new SmoothScrollLinearLayoutManager(getContext(), LinearLayoutManager.VERTICAL, false));
recyclerView.setHasFixedSize(false);
recyclerView.setItemAnimator(null);
if (adapter == null) {
    adapter = new AddressBookAdapter(contactsWithHeaders, this, this.contactRefIds, sortedByUpdatesCount);
    recyclerView.setAdapter(adapter);
    adapter.notifyDataSetChanged(); // to prevent list from scrolling down

    adapter.setDisplayHeadersAtStartUp(true);
    adapter.enableStickyHeaders();
} else {
    adapter.updateDataSet(contactsWithHeaders);
}
```

**Comment by davideas** [comment]
Hello @jonathanyee, this was already reported some months ago. It looks like you ddidn't set `true` the boolean to the `super()` call in the ViewHolder of the Header item.
This extra parameter is false by default to keep lighter the layout for views, because when set `true` an extra layout wraps the user layout, and it's not nice to add extra layout to all normal views.

Unfortunately, it's really impossible to inherit this value automatically from the instance and `itemView` is declared final in the official ViewHolder, we cannot change it anymore therefore it must be done in the constructor. To do so, the user has to add an extra parameter. Documentation has been written already.

If it's not this parameter, then it is something really strange we need to investigate.

**Comment by jonathanyee** [comment]
Thank you that fixed it, I must have missed this in the change log when I upgraded
