### ISSUE TITLE
Attempt to invoke virtual method 'android.view.ViewPropertyAnimator android.view.ViewGroup.animate()' on a null object reference

### ISSUE THREAD

**Issue by jonathanyee** [davideas/FlexibleAdapter#207]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewPropertyAnimator android.view.ViewGroup.animate()' on a null object reference
        at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.detachFromRecyclerView(StickyHeaderHelper.java:89)
        at eu.davidea.flexibleadapter.FlexibleAdapter.onDetachedFromRecyclerView(FlexibleAdapter.java:318)
        at android.support.v7.widget.RecyclerView.setAdapterInternal(RecyclerView.java:932)
        at android.support.v7.widget.RecyclerView.setAdapter(RecyclerView.java:915)
        at spokeo.com.spokeomobile.activity.contacts.AddressBookFragment.createAddressBookAdapter(AddressBookFragment.java:280)
        at spokeo.com.spokeomobile.activity.contacts.AddressBookFragment.retrieveContactsFromDB(AddressBookFragment.java:205)
        at spokeo.com.spokeomobile.activity.contacts.ContactsActivity$11.run(ContactsActivity.java:1299)
        at android.app.Activity.runOnUiThread(Activity.java:5524)
        at spokeo.com.spokeomobile.activity.contacts.ContactsActivity.connectionsFinished(ContactsActivity.java:1290)
        at spokeo.com.spokeomobile.server.NetworkAPI$ImportContactsTask.onPostExecute(NetworkAPI.java:280)
        at spokeo.com.spokeomobile.server.NetworkAPI$ImportContactsTask.onPostExecute(NetworkAPI.java:228)
        at android.os.AsyncTask.finish(AsyncTask.java:651)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5422)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I'm getting this null pointer when I am setting the adapter to the recyclerview.

```
recyclerView = (RecyclerView) getView().findViewById(R.id.list);
recyclerView.addItemDecoration(new ConnectionDividerDecoration(getContext(), 5));
recyclerView.setLayoutManager(new SmoothScrollLinearLayoutManager(getContext(), LinearLayoutManager.VERTICAL, false));
recyclerView.setHasFixedSize(false);
recyclerView.setItemAnimator(null);
if (adapter == null) {
    adapter = new AddressBookAdapter(contactsWithHeaders, this);
    recyclerView.setAdapter(adapter);

    adapter.notifyDataSetChanged(); // to prevent list from scrolling down
    adapter.setDisplayHeadersAtStartUp(true);
    adapter.enableStickyHeaders();

} else {
    adapter.updateDataSet(contactsWithHeaders);
}
```

Maybe its getStickySectionHeadersHolder?

```
public class AddressBookAdapter extends FlexibleAdapter<AbstractFlexibleItem> {

    private static String TAG = "AddressBookAdapter";

    private Fragment parent;

    public AddressBookAdapter(List<AbstractFlexibleItem> contactsWithHeaders, AddressBookFragment addrBookFragment) {
        super(contactsWithHeaders, addrBookFragment);

        this.parent = addrBookFragment;
    }

    @Override
    public ViewGroup getStickySectionHeadersHolder() {
        if (parent != null) {
            return (ViewGroup) parent.getView().findViewById(R.id.sticky_header_container2);
        } else {
            return null;
        }
    }
}
```

**Comment by davideas** [comment]
@jonathanyee, yes it's the `getStickySectionHeadersHolder()`, `mStickyHolderLayout` is null at line 89.
It happens when the RV detaches from the window, probably during the stop/destroying phase.

I take the opportunity to notify you that method has been improved, see issue #179.
It gives you a different and better way to set a custom container, directly from the Activity/Fragment, so you don't need to override it anymore.

Current Snapshot already supports the new `set` method.
