### ISSUE TITLE
Crash in StickyHeaderHelper class as if StickyHolderLayout was not included

### ISSUE THREAD

**Issue by nbortolussi** [davideas/FlexibleAdapter#231]
I have implemented sticky headers in multiple places and everything is working well for a large majority. I am unable to reproduce the following bug (got it in from Crashlytics from a SAMSUNG-SM-G900A running 5.1.1). It seems like the crash would be caused by the sticky header view container not being included in the layout (which would make mStickyHolderLayout null), but I am definitely including the requisite code <include layout="@layout/sticky_header_layout" /> directly after the RecyclerView in my layout. Seems to be pretty hard to debug since I can't reproduce it - any ideas?
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewPropertyAnimator android.view.ViewGroup.animate()' on a null object reference
       at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.clearHeaderWithAnimation(StickyHeaderHelper.java:240)
       at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.updateOrClearHeader(StickyHeaderHelper.java:119)
       at eu.davidea.flexibleadapter.FlexibleAdapter$AdapterDataObserver.updateOrClearHeader(FlexibleAdapter.java:4445)
       at eu.davidea.flexibleadapter.FlexibleAdapter$AdapterDataObserver.onChanged(FlexibleAdapter.java:4452)
       at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:10769)
       at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:6347)
       at eu.davidea.flexibleadapter.FlexibleAdapter.postUpdate(FlexibleAdapter.java:4627)
       at eu.davidea.flexibleadapter.FlexibleAdapter.updateDataSet(FlexibleAdapter.java:497)
       at eu.davidea.flexibleadapter.FlexibleAdapter.updateDataSet(FlexibleAdapter.java:466)
       at com.winering.wine.base.BaseAdapter.updateDataSet(BaseAdapter.java:139)
       at com.winering.wine.channels.channeldetails.ChannelDetailsFragment.swapData(ChannelDetailsFragment.java:155)
       at com.winering.wine.channels.channeldetails.ChannelDetailsPresenter$1.handleMessage(ChannelDetailsPresenter.java:44)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by nbortolussi** [comment]
Sorry - I see now another ticket that mentions that setAdapter must be calling enableStickyHeaders()

**Comment by davideas** [comment]
@nbortolussi, probably there's still something out of our control, I will release a new snapshot now, with a null check being sure of not crashing the execution. However, it was not supposed to be null that layout in that chain of call.

**Comment by davideas** [comment]
@nbortolussi, do you see this warning log `WARNING! ViewGroup for Sticky Headers unspecified! You must include.....` when `enablingStickyHeaders()`?

**Comment by nbortolussi** [comment]
@davideas no I don't see the warning, but also I have not been able to reproduce the crash. I have since moved all the enableStickyHeaders() calls to after setAdapter() is called. you don't think that will fix the problem?

**Comment by nbortolussi** [comment]
Interesting - I actually did just get the crash. It was only upon doing 'Instant Run' from Android Studio however. The warning you mentioned did show in the logs first.

``11-17 19:09:22.101 31482-31482/com.winering.wine W/StickyHeaderHelper: WARNING! ViewGroup for Sticky Headers unspecified! You must include @layout/sticky_header_layout or implement FlexibleAdapter.getStickySectionHeadersHolder() method

**Comment by davideas** [comment]
Yes, calling after Adapter is attached to RV should be enough, however I don't know if the warning is enough, maybe an IllegalStateException should block the developer before deploying the App.

**Comment by nbortolussi** [comment]
Agreed - thanks for the help. great library by the way, very well done 👍

**Comment by davideas** [comment]
@nbortolussi thank you!! I'm glad you resolved without any fix.
However, for the new checks I need to think a little, there are some others things linked, so I won't publish a new Snapshot now.
