### ISSUE TITLE
ClassCastException after click on expanded sticky header

### ISSUE THREAD

**Issue by szynka** [davideas/FlexibleAdapter#299]
I think i found bug in latest commit "AutoCollapseOnExpand", sometimes click on expanded sticky header i've got ClassCastException:
 ```
   java.lang.ClassCastException: eu.davidea.samples.flexibleadapter.items.SubItem$ChildViewHolder cannot be cast to eu.davidea.samples.flexibleadapter.items.ExpandableHeaderItem$ExpandableHeaderViewHolder
                                                                                       at eu.davidea.samples.flexibleadapter.items.ExpandableHeaderItem.bindViewHolder(ExpandableHeaderItem.java:27)
                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1870)
                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1840)
                                                                                       at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.updateHeader(StickyHeaderHelper.java:169)
                                                                                       at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.updateOrClearHeader(StickyHeaderHelper.java:143)
                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter$AdapterDataObserver.updateOrClearHeader(FlexibleAdapter.java:5232)
                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter$AdapterDataObserver.onItemRangeRemoved(FlexibleAdapter.java:5251)
                                                                                       at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeRemoved(RecyclerView.java:11104)
                                                                                       at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeRemoved(RecyclerView.java:6736)
                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.collapse(FlexibleAdapter.java:2708)
                                                                                       at eu.davidea.viewholders.ExpandableViewHolder.collapseView(ExpandableViewHolder.java:153)
                                                                                       at eu.davidea.samples.flexibleadapter.items.ExpandableHeaderItem$ExpandableHeaderViewHolder.collapseView(ExpandableHeaderItem.java:238)
                                                                                       at eu.davidea.viewholders.ExpandableViewHolder.toggleExpansion(ExpandableViewHolder.java:124)
                                                                                       at eu.davidea.samples.flexibleadapter.items.ExpandableHeaderItem$ExpandableHeaderViewHolder.toggleExpansion(ExpandableHeaderItem.java:209)
                                                                                       at eu.davidea.viewholders.ExpandableViewHolder.onClick(ExpandableViewHolder.java:171)
```

**Comment by davideas** [comment]
Thanks @szynka, latest commit resolved in part the problem of notification of autoCollapse, but notifying before the delete notifications seems not good, so I inverted them.

**Comment by davideas** [comment]
it doesn't occur anymore, I hope you can confirm.

**Comment by davideas** [comment]
This issue still occurs, but it is connected to the resolution of 295, since it is part of the same development. So I keep closes anyway.
