### ISSUE TITLE
Allow to use custom LayoutManagers on the RecyclerView

### ISSUE THREAD

**Issue by Christophe668** [davideas/FlexibleAdapter#302]
Hi, 

I'd like to report a crash that happens while the library tries to bind a view if we use a LayoutManager different than a LinearLayoutManager or StaggeredGridLayoutManager.
This is happening on the version _5.0.0-rc1_ and _5.0.0-SNAPSHOT built on 2017.02.15_. 

Here's the StackTrace I'm getting :

```
java.lang.ClassCastException: com.beloo.widget.chipslayoutmanager.ChipsLayoutManager cannot be cast to android.support.v7.widget.LinearLayoutManager
at eu.davidea.flexibleadapter.utils.Utils.findLastVisibleItemPosition(Utils.java:347)
at eu.davidea.flexibleadapter.AnimatorAdapter.animateView(AnimatorAdapter.java:369)
at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1880)
at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6312)
at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5258)
at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5521)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5363)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5359)
at com.beloo.widget.chipslayoutmanager.ChipsLayoutManager.fillWithLayouter(ChipsLayoutManager.java:858)
at com.beloo.widget.chipslayoutmanager.ChipsLayoutManager.fill(ChipsLayoutManager.java:821)
at com.beloo.widget.chipslayoutmanager.ChipsLayoutManager.onLayoutChildren(ChipsLayoutManager.java:719)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3506)
at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2969)
```

Thank you !

**Comment by davideas** [comment]
@Christophe668, so ChipsLayoutManager doesn't extend from Linear.
Can you make it extend from it? What ChipsLayout does?

**Comment by Christophe668** [comment]
It's a external library I'm using to display content as a flow in a recyclerView:
https://github.com/BelooS/ChipsLayoutManager

There's also an equivalent developed by Google (still in development) : https://github.com/google/flexbox-layout/blob/master/RecyclerView.md

Which is also using a custom implementation of the LayoutManager :

https://github.com/google/flexbox-layout/blob/dev_recyclerview/flexbox/src/main/java/com/google/android/flexbox/FlexboxLayoutManager.java

**Comment by davideas** [comment]
Then, I need to add new feature to give possibility to set a custom layout manager, so that doesn't occur, but I'm fear you can't use features like sticky headers or something else.

**Comment by Christophe668** [comment]
I understand if there are incompatibilities with other features. 
I mainly use your library to help reduce boilerplate code with adapters :)

**Comment by davideas** [comment]
@Christophe668, i will think about it.

**Comment by davideas** [comment]
Custom layout manager are now supported, it will be available from next Snapshot.
You'll need to implement the `IFlexibleLayoutManager`.
