### ISSUE TITLE
ClassCastException when the library call item's `onBindViewHolder`

### ISSUE THREAD

**Issue by IHNEL** [davideas/FlexibleAdapter#303]
This is my first try on the library. I thought this is very awesome library, thank you.
I try to implement a sectionable recycler-view, spent 2 days to read through wiki and the example but can't fix the issue myself.  
I initialize the adapter with null data-list then add one by one later. If I remove the setting `setDisplayHeadersAtStartUp(true)`, the recycler works without header. It shows data-item only. If I add this setting, the app crash with `ClassCastException`. Please help to take a look. Thanks
```
upcomingAdapter = new FlexibleAdapter<>(null);
recyclerView.setAdapter(upcomingAdapter);
 upcomingAdapter.setDisplayHeadersAtStartUp(true);

//On data loading callback:
MyHeader headerItem = new MyHeader(task.deadlines.get(0).date);
MyItem item = new MyItem(task, headerItem);
upcomingAdapter.addItem(item);
```

```
   public class MyHeader extends AbstractHeaderItem<MyHeader.HeaderVH> {
        public final ObservableLong date = new ObservableLong();

        MyHeader(long date) {
            this.date.set(date);
            this.setHidden(false);
        }

        @Override
        public HeaderVH createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater, ViewGroup parent) {
            View view = inflater.inflate(R.layout.view_upcoming_task_header_item, parent, false);
            return new HeaderVH(view, adapter);
        }

        @Override
        public void bindViewHolder(FlexibleAdapter adapter, HeaderVH holder, int position, List payloads) {

        }

        @Override
        public boolean equals(Object o) {
            if (o instanceof MyHeader) {
                return ((MyHeader) o).date.get() == this.date.get();
            }
            return false;
        }

        public class HeaderVH extends FlexibleViewHolder {
            public HeaderVH(View view, FlexibleAdapter adapter) {
                super(view, adapter, true);
            }

        }
    }

    class MyItem extends AbstractSectionableItem<MyItem.ItemVH, MyHeader> {
        Task task;

        MyItem(Task task, MyHeader header) {
            super(header);
            this.task = task;
        }

        @Override
        public boolean equals(Object o) {
            return false;
        }

        @Override
        public ItemVH createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater, ViewGroup parent) {
            ViewUpcomingTaskItemBinding binding = DataBindingUtil.inflate(inflater, R.layout.view_upcoming_task_item, parent, false);
            return new ItemVH(binding, adapter);
        }

        @Override
        public void bindViewHolder(FlexibleAdapter adapter, ItemVH holder, int position, List payloads) {
            holder.bindData(task);
        }


        class ItemVH extends FlexibleViewHolder {
            ViewUpcomingTaskItemBinding mBinding;

            public ItemVH(ViewUpcomingTaskItemBinding binding, FlexibleAdapter adapter) {
                super(binding.getRoot(), adapter);
                mBinding = binding;
            }

            void bindData(Task dataItem) {
                mBinding.setTask(dataItem);
            }
        }
    }
```

Here is the logcat:

```
 java.lang.ClassCastException: com.makeit.lite.main.upcoming.UpcomingFragment$UpcomingHeaderItem$HeaderVH cannot be cast to com.makeit.lite.main.upcoming.UpcomingFragment$UpcomingItem$ItemVH
at com.makeit.lite.main.upcoming.UpcomingFragment$UpcomingItem.bindViewHolder(UpcomingFragment.java:166)
at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1867)
at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6341)
at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5287)
at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5550)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2979)
at android.view.View.measure(View.java:18788)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:18788)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
at android.view.View.measure(View.java:18788)
at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
at android.view.View.measure(View.java:18788)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
at android.view.View.measure(View.java:18788)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
at android.view.View.measure(View.java:18788)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
at android.view.View.measure(View.java:18788)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:18788)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
at android.view.View.measure(View.java:18788)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
at android.view.View.measure(View.java:18788)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858
02-27 01:45:30.314 28658-28672/com.makeit.lite I/art: Starting a blocking GC Explicit
02-27 01:45:30.321 28658-28672/com.makeit.lite I/art: Explicit concurrent mark sweep GC freed 23301(1736KB) AllocSpace objects, 2(32KB) LOS objects, 24% free, 5MB/7MB, paused 106us total 6.685ms
02-27 01:50:27.232 28658-28658/? I/Process: Sending signal. PID: 28658 SIG: 9

```

**Comment by davideas** [comment]
@IHNEL, this is not good:
```
@Override
public boolean equals(Object o) {
    return false;
}
```
Also `upcomingAdapter` should use a common item type, such as `AbstractFlexibleItem`, because you are using a multi-type list.

**Comment by IHNEL** [comment]
Thank you for quick response. But sorry, I still don't understand what should I do. That `equals` return false since the items are different each others. 
And, What do you mean regarding the `upcomingAdapter`? I want to create a collapsable + sticky header list. Where I can add different items inside. The items in a group are those have same property (such as type-id). What should I do ?

**Comment by davideas** [comment]
@IHNEL, sorry but that is Java. `equals` compares different objects in a list or between them, if it returns always false, that object will never be picked up. Use can use default java implementation `return this == o`.
- Better to not alter the hidden property, it is used by the adapter internally.
- Header should implement `IHeader`, Wiki and demo are clear.
- You are adding one by one, but you still need to pass a copy of the list to the adapter.
- Probably you don't need to extend FlexibleAdapter, just pass the copy of the list to it, once you built it.

**Comment by IHNEL** [comment]
@davideas 
Sorry to said that the actually problem is I didn't implement method `getLayoutRes`. I inflate the layout directly in `createViewHolder`. This work fine if I use flat list, crash in case of Sectionable list with crash-log above.

I think it would be great if we ask `getLayoutRes` have been implemented in crash log instead of `java.lang.ClassCastException`

**Comment by davideas** [comment]
@IHNEL, so those 3 methods should be declared abstract (maybe).

**Comment by IHNEL** [comment]
Exactly what I mean. This approach will help to save lot of time for who may run into similar case.
