### ISSUE TITLE
Filtering issue during delete search query

### ISSUE THREAD

**Issue by tprochazka** [davideas/FlexibleAdapter#328]
I'm trying to implement list filterings on version 5.0.0-rc1.

It works good until I will try to delete search query. Then it should found more items, but it always crash during the add new items to the list with the stack trace bellow. But it works in your demo and I'm not able to found reason.  I just now that in the list was 99 item and when I delete on character from query 100 items was qualified and should appear in the list. I'm using sticky headers.

And I don't understand why I must provide unfiltered items to the filterItems(), why it can't use items which are already in the adapter? I'm using method addItem() and adItems() so I don't have current state of all items.

```
 Caused by: java.lang.IndexOutOfBoundsException: Index: 100, Size: 99
                                                                                       at java.util.ArrayList.add(ArrayList.java:457)
                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.applyAndAnimateAdditions(FlexibleAdapter.java:4270)
                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.animateTo(FlexibleAdapter.java:4193)
                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.animateDiff(FlexibleAdapter.java:4167)
                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.filterItemsAsync(FlexibleAdapter.java:3974)
                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter.access$2100(FlexibleAdapter.java:98)
                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter$FilterAsyncTask.doInBackground(FlexibleAdapter.java:5287)
                                                                                       at eu.davidea.flexibleadapter.FlexibleAdapter$FilterAsyncTask.doInBackground(FlexibleAdapter.java:5253)
                                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                       at java.lang.Thread.run(Thread.java:761) 
```

**Comment by tprochazka** [comment]
So I found the reason. List provided to the filterItems() contains more items that the original list that was inside of the adapter before search. 

And I found another issue, sticky grid are not sticky during to search. It has some reason?

**Comment by davideas** [comment]
@tprochazka it could be if they are not synced.

Regarding deactivating sticky, yes I made with a reason: if I keep the sticky it will crash 100%.
I do not remember exactly the exception, but not easy to have both functionalities at the same time.

**Comment by mdtuyen** [comment]
Hi @davideas , I have same issue, what is solution for this case. I can't use sticky here ?

**Comment by davideas** [comment]
It might be a little bug, need to check it better, could you provide me the logs as well?
Just I don't have time, I try to do my best.

> And I don't understand why I must provide unfiltered items to the filterItems(), why it can't use items which are already in the adapter? I'm using method addItem() and addItems() so I don't have current state of all items.

Normally, you have your original list, it is necessary to pick up items to add in the adapter list when you delete characters in the search text.
But indeed I might create a copy of the original list internally, but if you search remotely then you need to provide a new list, and you are also using a loading more, so not all items are displayed, in this case what should I keep as original list?

**Comment by bafitor** [comment]
Hi guys.

I had the same exact issue and the root cause was a incorrect implementation of the _hashCode()_ and _equals()_ methods in the adapter items.

That fix solved the issue for me.

**Comment by tprochazka** [comment]
I don't understand why sticky grid during the search is problem. It is nothing special, you just display less item. If I will do async search myself and the just update data in the adapter it will works. Of course use integrated search is much easier, than do it myself.

And related to necessary to provide again original list for search.  

> Normally, you have your original list, it is necessary to pick up items to add in the adapter list when you delete characters in the search text.
> But indeed I might create a copy of the original list internally, but if you search remotely then you need to provide a new list, and user might also be using a Loading more feature, so not all items are displayed, in this case what should I keep as original list?

Would be great if it will create copy automatically as default option and there will be optional way to provide own list when it is needed.

**Comment by davideas** [comment]
@tprochazka:
> I don't understand why sticky grid during the search is problem. It is nothing special, you just display less items.

Yes, when you add characters you always reduce the current list, but when you delete characters you need the original list to reinsert items, those items are lost during the filter. So what you suggest is just half search.

> Would be great if it will create copy automatically as default option and there will be optional way to provide own list when it is needed.

It could be an improvement. Default internal copy is done when searchText is initially inserted and list of items restored if searchText is cleared out. To use a custom list to start the filter can be done with just simply passing the new list as it is now.
I will open a new issue for this improvement.
