### ISSUE TITLE
Wrong position when removing multiple items

### ISSUE THREAD

**Issue by henengel** [davideas/FlexibleAdapter#329]
Hi David, in continuation to other issues we worked on last week, I encountered this one too.
Since it's an issue that is not related to other issues we had, I thought it would be better to open a new ticket to better address the problem, and for other users to be able to solve this particular issue in case they have it too.
The problem I have is the position I get in `onBindViewHolder`when removing multiple items.
Scenario:
I create multiple DFP banners ad requests. 
Inside the onBind method, I have a listener that is invoked if the banner fails to load. In that case, I try to remove the item.

Relevant code:
At first I tried:
```java
mDataUtils.removeItemFromData(position);
adapter.notifyItemRemoved(position);
adapter.notifyItemRangeChanged(position, mDataUtils.getCurrentDataSet().size());
```
In other isuues to say that there is no need to use notify*** mehtods, so I then tried:

```java
mDataUtils.removeItemFromData(position);
adapter.updateDataSet(new ArrayList(mDataUtils.getCurrentDataSet()),false);
```
Both didn't do the trick.

The issue:
When removing the first item of multiple ones, the position I get in the `onBindViewHolder` method of the item is ok and no problem.

After that, every other item I remove, the position of the item I get is invalid.
I think it has to do with the range not being updated and hence, resulting in getting the wrong position of the item.

Any suggestions?
#324

**Comment by henengel** [comment]
@davideas David?

**Comment by davideas** [comment]
@henengel, you have the method `getGlobalPositionOf(item)`, then you can call `removeItem(position)`, notification is inside. That's it.

**Comment by henengel** [comment]
@davideas Do it as you said, in the `onBindViewHolder()`using the code:
```java
int globalPosition = adapter.getGlobalPositionOf(DataUtils.getInstance().getCurrentDataSet().get(position));
            DataUtils.getInstance().removeItemFromData(globalPosition);
            adapter.removeItem(position);
```
or:
```java
int globalPosition = adapter.getGlobalPositionOf(DataUtils.getInstance().getCurrentDataSet().get(position));
            DataUtils.getInstance().removeItemFromData(globalPosition);
            adapter.removeItem(globalPosition);
```
* Not sure which one to use?

The app crashes with this stack trace:

> java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
                                                               at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2530)
                                                               at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeRemoved(RecyclerView.java:4913)
                                                               at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeRemoved(RecyclerView.java:11135)
                                                               at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeRemoved(RecyclerView.java:6767)
                                                               at eu.davidea.flexibleadapter.FlexibleAdapter.removeRange(FlexibleAdapter.java:3440)
                                                               at eu.davidea.flexibleadapter.FlexibleAdapter.removeItem(FlexibleAdapter.java:3235)
                                                               at eu.davidea.flexibleadapter.FlexibleAdapter.removeItem(FlexibleAdapter.java:3213)
                                                               at cambium.com.il.sport5.models.feed_item.UrlBannerItem.bindViewHolder(UrlBannerItem.java:83)
                                                               at cambium.com.il.sport5.models.feed_item.UrlBannerItem.bindViewHolder(UrlBannerItem.java:23)
                                                               at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1867)
                                                               at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6343)
                                                               at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5289)
                                                               at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5552)
                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
                                                               at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                               at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                               at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3537)
                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3266)
                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
                                                               at android.view.View.layout(View.java:17735)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                               at android.view.View.layout(View.java:17735)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                               at android.view.View.layout(View.java:17735)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                               at android.view.View.layout(View.java:17735)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                               at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                               at android.view.View.layout(View.java:17735)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                               at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                                               at android.view.View.layout(View.java:17735)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                               at android.view.View.layout(View.java:17735)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                               at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                               at android.view.View.layout(View.java:17735)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5579)
04-05 16:20:59.383 cambium.com.il.sport5 E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                               at android.view.View.layout(View.java:17735)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                               at android.view.View.layout(View.java:17735)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                               at android.view.View.layout(View.java:17735)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                               at android.view.View.layout(View.java:17735)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                               at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                               at android.view.View.layout(View.java:17735)
                                                               at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                               at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2380)
                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1280)
                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6432)
                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                               at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:154)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6290)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by henengel** [comment]
@davideas Should I use `removeItemWithDelay()` with `position` or `globalPosition`? (Does it matter?)

**Comment by davideas** [comment]
globalPosition is the real one for the Adapter point of view.

**Comment by davideas** [comment]
I do not know where `position` comes from, but you should use `DataUtils.getInstance().removeItemFromData(position);` since you got the item with that.

**Comment by henengel** [comment]
@davideas the `position` is the one provided by the `onBindViewHolder` method.

**Comment by davideas** [comment]
Then the position you have is already the adapter position, you don't need getGlobalPosition...
So you can't use for your Data.

**Comment by henengel** [comment]
@davideas 
> So you can't use for your Data.
What do mean?

So just remove the item from the adapter and the dataset with `position`?

**Comment by davideas** [comment]
Only from Adapter, and if you need to remove from your dataset:
```
item = adapter.getItem(position)
dataset.remove(item)
```

**Comment by henengel** [comment]
@davideas Correct me if I am mistaken but since the adapter is synced all the time with the dataset held in the datamanager singleton (Since Parcable/Serializable) can't be used, the dataset has to identical and up to date, no?

**Comment by davideas** [comment]
Depends what you keep in your dataset, so with that it never goes in exception.

**Comment by henengel** [comment]
@davideas Sorry David, but still, doing as you said doesn't make the adapter work properly. 
I'll try again to be as specific as I can.
There are multiple item types in the dataset. t
Some of them are adMob items.
In some cases (like if adBlock is installed) all those items are removed.
**Still**, when clicking on some items, I get `classCast`exeptions.

Code:
UrlBanner item `onBindViewHolder`:
```java
@Override
    public void bindViewHolder(final FlexibleAdapter adapter, UrlBannerViewHolder holder, final int position, List payloads) {

        if (AdsUtils.getInstance().getUrlBannerDataSetItem(String.valueOf(position)) != null){
            UrlBannerDataSetItem item = AdsUtils.getInstance().getUrlBannerDataSetItem(String.valueOf(position));

            if (item != null && item.isResponse()){
                try {
                    int feedHeight = GeneralUtils.getInstance().pxToDp(Integer.valueOf(item.getHeight()));
                    holder.updateSize(feedHeight);
                } catch (NumberFormatException e) {
                    holder.updateSize(0);
                }

                PublisherAdView ad = item.getAdView();
                holder.adView.addView(ad);
            }
            else {

                adapter.removeItemWithDelay(adapter.getItem(position),500, true);
            }
        }
        else {
            adapter.removeItemWithDelay(adapter.getItem(position),500, true);
        }
    }
```

XmlBanner `onBindViewHolder`:
```java
 @Override
    public void bindViewHolder(final FlexibleAdapter adapter, final XmlBannerViewHolder holder, final int position, List payloads) {

        if (AdsUtils.getInstance().getXmlBannerDataSetItem(String.valueOf(position)) != null){
            XmlBannerDataSetItem item = AdsUtils.getInstance().getXmlBannerDataSetItem(String.valueOf(position));
            if (item != null && item.isResponse()){
                NativeContentAdView adView = (NativeContentAdView) mLayoutInflater
                        .inflate(R.layout.item_main_feed_xml_banner_content, null);
                populateContentAdView(item.getNativeContentAd(), adView);
                holder.xmlBannerContainer.removeAllViews();
                holder.xmlBannerContainer.addView(adView);
            }
            else {

                adapter.removeItemWithDelay(adapter.getItem(position),500, true);
            }
        }
        else {
            adapter.removeItemWithDelay(mDataUtils.getCurrentDataSet().get(position),500, true);
        }
    }
```
Dataset passed to the adapter when creating it:

![image](https://cloud.githubusercontent.com/assets/13081692/24739407/7afe3f22-1aa4-11e7-9e67-04f259ef9836.png)

When clicking the item the was originally in index 7 (WebViewItem), this is all the relevant info at moment of clicking the item:

Adapter items dataset state at the moment of clicking the item:

![image](https://cloud.githubusercontent.com/assets/13081692/24739701/f41bca22-1aa5-11e7-8787-2c45e574ea73.png)

Item info when clicking it (original webview item has moved to index 5 after UrlBanner item that was at index 1 and XmlBanner item that was at index 5 have been removed):

![image](https://cloud.githubusercontent.com/assets/13081692/24739661/c31a68f2-1aa5-11e7-8cfb-39a658c82a35.png)

Code executed when clicking the WebView item:

```java
@Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {

                UrlType urlType = new UrlType(Type.WEB_ITEM, url, (AbstractItem) adapter.getItem(position));
                mUrlNavigationManager.handleUrl(urlType);

                mAdsUtils.setInterstitialAdsCounter(urlType.getUrl());

                return true;
            }
```



After all this, when executing the code, I get the exeption:
> java.lang.ClassCastException: cambium.com.il.sport5.models.feed_item.SectionItem cannot be cast to cambium.com.il.sport5.models.feed_item.AbstractItem
                                                               at cambium.com.il.sport5.models.feed_item.WebViewItem$1.shouldOverrideUrlLoading(WebViewItem.java:96)
                                                               at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
                                                               at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:354)
                                                               at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:168)
                                                               at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:352)
                                                               at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                               at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:154)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6290)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by henengel** [comment]
@davideas Please read carefully everything and if you don't understand something or need more info, please ask.

**Comment by davideas** [comment]
Sorry @henengel, please use Snapshot version (published yesterday eve) if you consider it better, read last post in issue 39 for release notes. I will be busy for the time being.

Regarding the ClassCast it will take some time and debugging from your side, better if you search on Internet.
I see that the codes references are completely different in the 2 lists you've shown me. So they are different object in memory too. _I really do not know how your use case works and the whole code running behind_.
