### ISSUE TITLE
Sample app java.lang.IndexOutOfBoundsException at Expandable Sections

### ISSUE THREAD

**Issue by MrOnyszko** [davideas/FlexibleAdapter#345]
Hi, I spot a bug in sample application at Expandable Sections. 

I was manipulating the items and headers and application crashed with stacktrace below. I was testing on OnePlus X.

It's really easy to reproduce look at [video](https://github.com/davideas/FlexibleAdapter/files/924474/device-2017-04-16-202254.mp4.zip)

Thanks for your effort and I wish you good results with this great library!

```java 04-16 20:07:07.161 24478-24478/eu.davidea.examples.flexibleadapter E/AndroidRuntime: FATAL EXCEPTION: main
Process: eu.davidea.examples.flexibleadapter, PID: 24478
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 9(offset:-1).state:255
at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5458)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3488)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1633)
at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:341)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
at android.view.Choreographer.doCallbacks(Choreographer.java:670)
at android.view.Choreographer.doFrame(Choreographer.java:603)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5539)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by davideas** [comment]
@MrOnyszko, yeah, I reproduced it by moving only the _Sub Item 1_ out of its parent.
The reason is very simple: the code to move the sub item from a parent to another is not done, so when a parent collapses it removes the number of elements below it as much as the sub list size, of course it doesn't like.

So it's not a bug of the Library, just missing code.

**Comment by MrOnyszko** [comment]
@davideas I understand, I suppose that you are going to add that missing code? ;)

**Comment by davideas** [comment]
Sorry @MrOnyszko, maybe 1 day, not soon. But everyone can do it.
