### ISSUE TITLE
LayoutManager must be initialized before setting FlexibleAdapter for RecyclerView

### ISSUE THREAD

**Issue by yamelkaya** [davideas/FlexibleAdapter#350]
As I see LayoutManager should be assigned before setting adapter otherwise I had an exception: 

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.widget.LinearLayoutManager.findLastVisibleItemPosition()' on a null object reference
                                                                     at eu.davidea.flexibleadapter.common.FlexibleLayoutManager.findLastVisibleItemPosition(FlexibleLayoutManager.java:133)
                                                                     at eu.davidea.flexibleadapter.AnimatorAdapter.animateView(AnimatorAdapter.java:369)
                                                                     at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1906)
                                                                     at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                     at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
                                                                     at android.view.View.measure(View.java:18788)
                                                                     at android.widget.RelativeLayout.measureChild(RelativeLayout.java:676)
                                                                     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:479)
                                                                     at android.view.View.measure(View.java:18788)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                     at com.github.aakira.expandablelayout.ExpandableLinearLayout.onMeasure(ExpandableLinearLayout.java:109)
                                                                     at android.view.View.measure(View.java:18788)
                                                                     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                     at android.view.View.measure(View.java:18788)
                                                                     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                     at android.view.View.measure(View.java:18788)
                                                                     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                     at android.view.View.measure(View.java:18788)
                                                                     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                     at android.view.View.measure(View.java:18788)
                                                                     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                     at android.view.View.measure(View.java:18788)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                     at android.view.View.measure(View.java:18788)
                                                                     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
                                                                     at android.view.View.measure(View.java:18788)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                     at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
                                                                     at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:786)
                                                                     at android.view.View.measure(View.java:18788)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
```
I haven't find this information mentioned in wiki or in migration notes. Maybe it need to be mentioned or I missed something?

**Comment by davideas** [comment]
@yamelkaya, yes thank you. I will initialize it separately if needed.
