### ISSUE TITLE
Section Header - Clicks cause ClassCastException in a list of Items

### ISSUE THREAD

**Issue by huangwaylon** [davideas/FlexibleAdapter#360]
Thanks for this useful library!

I have a list of items that extend AbstractFlexibleItem. These items implement ISectionable.
I also have some headers that extend AbstractHeaderItem.

```
final List<WordFragmentItem> items = getListOfItems(jamoDBManager);
final FlexibleAdapter<WordFragmentItem> adapter = new FlexibleAdapter<WordFragmentItem>(items);
```

For each item in my list of items, I set the header to be one of the AbstractHeaderItems.

Now I simply pass my list of items to a FlexibleAdapter.

However, I would like to add an on click listener:
```
adapter.addListener(new FlexibleAdapter.OnItemClickListener() {
    @Override
    public boolean onItemClick(int position) {
        // Check that the listener is non null.
        if (mListener != null) {
            mListener.onListFragmentInteraction(items.get(position).getId());
        }
        return true;
    }
});
```

The problem is, items is a list of only AbstractFlexibleItems. But the recyclerview has AbstractFlexibleItems and AbstractHeaderItems (for the section headers). Also, these section headers are sticky. When I click a section header, I get the following exception:

```
java.lang.ClassCastException: com.wayway.hr.WordFragmentHeader cannot be cast to com.wayway.hr.WordFragmentItem
    at com.wayway.hr.WordFragment$1.onItemClick(WordFragment.java:97)
    at eu.davidea.viewholders.FlexibleViewHolder.onClick(FlexibleViewHolder.java:121)
    at android.view.View.performClick(View.java:5265)
    at android.view.View$PerformClick.run(View.java:21534)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:5728)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

This makes sense since I'm clicking a section header, but it can't be cast to an item.

How can I disable section header clicks? Is there a better solution to this approach? 
If I wanted section header clicks, how do I create a separate on click listener for them?

Thanks!

**Comment by davideas** [comment]
@huangwaylon, you welcome.

For that bug, please read [migrations](./wiki/migrations) and use the Snapshot version. It shouldn't happen anymore.

Later on, you can also disable the item from the inside `setEnabled(false)` so it won't react to any taps. You can them add any click listener to any inner view you want, just follow the steps in this issue #326.
In the demo App, there's an click listener on the header title, you can check it out.

**Comment by huangwaylon** [comment]
Thanks for the response! I chose to use setEnabled(false) which worked fine as I don't need to react to section taps at this time.
