### ISSUE TITLE
All your apks NOT WORK, DUDE

### ISSUE THREAD

**Issue by goodandrewsoft** [davideas/FlexibleAdapter#375]
2 last apks - not work on emulator and 19 api phone.
apk from arsenal - not work too. You are RIDICOLOUS.... 
good by !!!

FATAL EXCEPTION: main
                                                                                     Process: eu.davidea.examples.flexibleadapter, PID: 22301
                                                                                     java.lang.NoClassDefFoundError: com.android.tools.fd.runtime.AppInfo
                                                                                         at com.android.tools.fd.runtime.BootstrapApplication.<init>(BootstrapApplication.java:119)
                                                                                         at java.lang.Class.newInstanceImpl(Native Method)
                                                                                         at java.lang.Class.newInstance(Class.java:1208)
                                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:990)
                                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                                                         at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301)
                                                                                         at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                         at dalvik.system.NativeStart.main(Native Method)

**It is ONE of many problems, only ONE**

**Comment by thelong1EU** [comment]
@goodandrewsoft learn English my dear

**Comment by goodandrewsoft** [comment]
It's not about me, my darling.

**Comment by thelong1EU** [comment]
I'm not waisting my time on this. I was just intrigued by the way you made you point.

**Comment by goodandrewsoft** [comment]
Ok, now you can pass by.

**Comment by davideas** [comment]
@goodandrewsoft, please use the snapshot version from the code (and emulator) if you want to check it out. Which is the one I am working on for the RC2 release.
I'm not going to modify them because too old. Probably I will delete them once I will publish the new pre-release.

PS. And man, I do not like the tone of your message. You have to consider others point of views.

**Comment by NightSkyDev** [comment]
Hi @davideas ... this is probably a good place to state that I really appreciate your project and all the hard work you've put in to this library!  I'm using your library for on a new project because I need Sticky Headers and I can say - your stuff really does work!  Thank you.
