### ISSUE TITLE
Internal Log causes java.lang.NullPointerException when compiled with ProGuard

### ISSUE THREAD

**Issue by volser** [davideas/FlexibleAdapter#387]
Running version 5.0.0-rc2 built on 2017.06.10

with PRO GUARD

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
                                         at eu.davidea.flexibleadapter.utils.Log.getTag(Unknown Source)
                                         at eu.davidea.flexibleadapter.utils.Log.i(Unknown Source)
                                         at eu.davidea.flexibleadapter.FlexibleAdapter.addListener(Unknown Source)
                                         at co.mangotechnologies.clickup.adapters.a.addListener(Unknown Source)
                                         at eu.davidea.flexibleadapter.FlexibleAdapter.<init>(Unknown Source)

**Comment by davideas** [comment]
@volser, thanks for reporting.

Could you please add the following lines in the _pro-guard_ file as the [pro-guard manual](https://www.guardsquare.com/en/proguard/manual/examples#stacktrace) states?

> We're keeping all source file attributes, but we're replacing their values by the string "SourceFile". We could use any string. This string is already present in all class files, so it doesn't take up any extra space.
>
> We're also keeping the line number tables of all methods.
>
> Whenever both of these attributes are present, the Java run-time environment will include line number information when printing out exception stack traces.
```
-printmapping out.map
-renamesourcefileattribute SourceFile 
-keepattributes SourceFile,LineNumberTable
```

In the mean time I provide a fix for future releases.

**Comment by davideas** [comment]
However, the default internal log has a `SUPPRESS` feature, but I forgot to set it as default value for the level, you can also do the following, it should fix as well the problem with pro-guard, because the log will never be executed;
``` java
if (BuildConfig.DEBUG) {
    Log.setLevel(Level.INFO);
} else {
    Log.setLevel(Level.SUPPRESS);
}
```

**Comment by volser** [comment]
yeah thanks, I already set  Log.setLevel
I created issue to fix for future
