### ISSUE TITLE
Bug on Sample App

### ISSUE THREAD

**Issue by boyfox** [davideas/FlexibleAdapter#40]
When clicking sub item or remove sub item, will be appear following error:

`FATAL EXCEPTION: main
	Process: eu.davidea.examples.flexibleadapter, PID: 28911
	java.lang.ClassCastException: eu.davidea.examples.models.SubItem cannot be cast to eu.davidea.examples.models.SimpleItem
	at eu.davidea.examples.flexibleadapter.MainActivity.extractTitleFrom(MainActivity.java:739)
	at eu.davidea.examples.flexibleadapter.MainActivity.onItemSwipe(MainActivity.java:492)
	at eu.davidea.flexibleadapter.FlexibleAdapter.onItemSwiped(FlexibleAdapter.java:2331)
	at eu.davidea.flexibleadapter.helpers.ItemTouchHelperCallback.onSwiped(ItemTouchHelperCallback.java:159)
	at android.support.v7.widget.helper.ItemTouchHelper$4.run(ItemTouchHelper.java:669)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Comment by davideas** [comment]
Yeah, thanks! It's trivial to solve it. I forgot the sub items when editing the title. I will do it during the day.

**Comment by davideas** [comment]
Yeah, thanks! It's trivial to solve it. I forgot the sub items when editing the title. I will do it during the day.

**Comment by boyfox** [comment]
Hi Davide!

I seen sample with " dev branch in beta: v5.0.0-b4 (usable library!)", but
here sections headers are not a sticky, sections header exists but moved
scrolling to up, i need to section header is standing while next header
comes up.

**Comment by davideas** [comment]
Hi, you need to activate that option from the top right menu.

Actually the headers, that are "sticky", are not clickable, I'm looking a
way to do it, not simple.

Davide

**Comment by boyfox** [comment]
Yes you are absolutely right!, sorry I forgot to look to menu. Thanks for
useful library!
