### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ouyangzn** [davideas/FlexibleAdapter#454]
Hi guys,
  I cloned this repository, and run flexible-adapter-app, but it crashed.
here is the log: 
`
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'eu.davidea.fastscroller.FastScroller eu.davidea.flexibleadapter.SelectableAdapter.getFastScroller()' on a null object reference
                                                                                      at eu.davidea.samples.flexibleadapter.MainActivity.onUpdateEmptyView(MainActivity.java:812)
                                                                                      at eu.davidea.flexibleadapter.FlexibleAdapter.addListener(FlexibleAdapter.java:299)
                                                                                      at eu.davidea.flexibleadapter.FlexibleAdapter.<init>(FlexibleAdapter.java:245)
                                                                                      at eu.davidea.samples.flexibleadapter.OverallAdapter.<init>(OverallAdapter.java:28)
                                                                                      at eu.davidea.samples.flexibleadapter.fragments.FragmentOverall.initializeRecyclerView(FragmentOverall.java:81)
                                                                                      at eu.davidea.samples.flexibleadapter.fragments.FragmentOverall.onActivityCreated(FragmentOverall.java:65)
                                                                                      at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2352)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                                                      at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
                                                                                      at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
                                                                                      at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
                                                                                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:552)
                                                                                      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                                                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                                                                                      at android.app.Activity.performStart(Activity.java:6696)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:154) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
`

**Comment by ouyangzn** [comment]
I found this is some error:

`MainActivity` implement `FlexibleAdapter.OnUpdateListener`
When load `FragmentOverall`, `new OverallAdapter(getActivity());` will trigger `onUpdateEmptyView()`.
And now adapter is not created finish , `mAdapter` is null.


![1](https://user-images.githubusercontent.com/8808376/30683927-d1ff036c-9ee1-11e7-8b0b-6aa9d35ef7db.png)

![2](https://user-images.githubusercontent.com/8808376/30683933-d3f7693e-9ee1-11e7-916c-2332fdb5a4cc.png)
![3](https://user-images.githubusercontent.com/8808376/30683937-d6122e98-9ee1-11e7-8be8-57d05099c05f.png)
![4](https://user-images.githubusercontent.com/8808376/30683942-d7ea3c60-9ee1-11e7-9676-3d799daadb56.png)
![5](https://user-images.githubusercontent.com/8808376/30683946-da88cb80-9ee1-11e7-8dc7-021ad941efa7.png)
![6](https://user-images.githubusercontent.com/8808376/30683952-dcd63a1c-9ee1-11e7-8da6-9075a23b88fc.png)

**Comment by davideas** [comment]
@ouyangzn, thanks, I recently modified something and didn't catch it.
