### ISSUE TITLE
Sticky headers adapter crashes when set with swapAdapter

### ISSUE THREAD

**Issue by NegreaVlad** [davideas/FlexibleAdapter#468]
I have a paginated adapter with sticky headers which works great. I now want to add search functionality to this. I do a search API call and I want to show the results in a new adapter, using swapAdapter. This helps me persist the already loaded paginated adapter.

`onAttachedToRecyclerView` gets called delayed on the new adapter and the app crashes when I enable the sticky headers.

```
    @Override
    public void onAgendasSearchedSuccessfully(ArrayList<GetAgendasResponse> agendasResponses, String term) {
        ArrayList<AbstractFlexibleItem> meetingListItems = mMeetingConvertionHelper.getMeetingListItems(agendasResponses, Collections.EMPTY_LIST);
        MeetingsAdapter flexibleAdapter = new MeetingsAdapter(meetingListItems, this);

        flexibleAdapter.setLoadingMoreAtStartUp(false)
                .setEndlessScrollState(false);

        mAgendasRV.swapAdapter(flexibleAdapter, true);

        flexibleAdapter.setNotifyMoveOfFilteredItems(true);
        flexibleAdapter.setUnlinkAllItemsOnRemoveHeaders(true)
                .setDisplayHeadersAtStartUp(true)
                .addListener(this);

       mAgendasRV.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
            @Override
            public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
                mAgendasRV.removeOnLayoutChangeListener(this);
                flexibleAdapter.setStickyHeaders(true)
                        .setStickyHeaderElevation(getResources().getDimension(R.dimen.dp8));
            }
        });

        hideLoadingScreen();
    }
```

I tried enabling the sticky headers after a layout change to delay it a bit.

I tried replicating this in the sample app, but I get a different error there. It crashes because of the adapter reference that is stored in `SimpleItem`:

```
10-13 20:03:38.331 17511-17511/eu.davidea.samples.flexibleadapter E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: eu.davidea.samples.flexibleadapter, PID: 17511
                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.widget.RecyclerView$LayoutManager android.support.v7.widget.RecyclerView.getLayoutManager()' on a null object reference
                                                                                        at eu.davidea.samples.flexibleadapter.items.SimpleItem$SimpleViewHolder.scrollAnimators(SimpleItem.java:215)
                                                                                        at eu.davidea.flexibleadapter.AnimatorAdapter.animateView(AnimatorAdapter.java:384)
                                                                                        at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1933)
                                                                                        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6387)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5343)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5606)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5448)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5444)
                                                                                        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                                        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                                        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                                        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                                        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3600)
                                                                                        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3329)
                                                                                        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3867)
                                                                                        at android.view.View.layout(View.java:17945)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                        at android.view.View.layout(View.java:17945)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                                                                        at android.view.View.layout(View.java:17945)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                        at android.view.View.layout(View.java:17945)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                                        at android.view.View.layout(View.java:17945)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                        at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                                        at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                                        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1397)
                                                                                        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                                        at android.view.View.layout(View.java:17945)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                                        at android.view.View.layout(View.java:17945)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                        at android.view.View.layout(View.java:17945)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                        at android.view.View.layout(View.java:17945)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                        at android.view.View.layout(View.java:17945)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                    	at andr
```

**Comment by NegreaVlad** [comment]
I had a bug in my code and the swapAdapter method was called in a loop multiple times in a short interval. The newly created adapter was already detached from the `RecyclerView` when I called `setStickyHeaders`
