### ISSUE TITLE
Feedback flexibleadapter problem

### ISSUE THREAD

**Issue by TCQQ** [davideas/FlexibleAdapter#482]
How to switch to load more status?, ex:（loaded successfully, loading failed, loading timeout ...）

**Comment by TCQQ** [comment]
package com.changrui.baseapp.activity;

import android.os.Bundle;
import android.support.v7.widget.DefaultItemAnimator;
import android.support.v7.widget.RecyclerView;

import com.changrui.baseapp.R;
import com.changrui.baseapp.adapter.items.OneItem;
import com.changrui.baseapp.model.DataModel;
import com.changrui.baseapp.utils.GsonUtils;
import com.changrui.framework.ui.activity.BaseActivity;

import java.util.ArrayList;
import java.util.List;

import butterknife.BindView;
import eu.davidea.flexibleadapter.FlexibleAdapter;
import eu.davidea.flexibleadapter.common.SmoothScrollLinearLayoutManager;
import eu.davidea.flexibleadapter.items.AbstractFlexibleItem;

/**
 * <pre>
 *     author : Alan
 *     e-mail : peijiarui@outlook.com
 *     time   : 2017/10/29
 *     desc   :
 * </pre>
 */
public class TestOneActivity extends BaseActivity implements FlexibleAdapter.OnItemClickListener {

    @BindView(R.id.recycler_view)
    RecyclerView mRecyclerView;

    FlexibleAdapter<AbstractFlexibleItem> mAdapter;

//    List<IFlexible> mList = new ArrayList<>();                          //数据列表
//    FlexibleAdapter<IFlexible> mAdapter = new FlexibleAdapter<>(mList); //适配器

    @Override
    protected int getLayoutId() {
        return R.layout.activity_test_one;
    }

    @Override
    protected void startUi(Bundle savedInstanceState) {
        super.startUi(savedInstanceState);

        String json = "{\n" +
                "    \"data\":[\n" +
                "        {\n" +
                "            \"type\":1,\n" +
                "            \"message\":\"Hello\"\n" +
                "        },\n" +
                "        {\n" +
                "            \"type\":2,\n" +
                "            \"message\":\"World\"\n" +
                "        }\n" +
                "    ]\n" +
                "}";


        DataModel resp = GsonUtils.gsonToModel(json, DataModel.class);

        final List<AbstractFlexibleItem> mItems = new ArrayList<>();

        for (int i = 0; i < resp.getData().size(); i++) {
            mItems.add(new OneItem(resp.getData().get(i)));
        }
        mAdapter.updateDataSet(mItems);


        mAdapter = new FlexibleAdapter<>(new ArrayList<AbstractFlexibleItem>(), this, true);

        mRecyclerView.setLayoutManager(new SmoothScrollLinearLayoutManager(this));
        mRecyclerView.setAdapter(mAdapter);
        mRecyclerView.setHasFixedSize(true);
        mRecyclerView.setNestedScrollingEnabled(false);
        mRecyclerView.setItemAnimator(new DefaultItemAnimator());
    }

    @Override
    public boolean onItemClick(int position) {
        System.out.println(position);
        return false;
    }
}

**Comment by TCQQ** [comment]
package com.changrui.baseapp.model;

import java.util.List;

public class DataModel {


    private List<DataBean> data;

    public List<DataBean> getData() {
        return data;
    }

    public void setData(List<DataBean> data) {
        this.data = data;
    }

    public static class DataBean {
        /**
         * type : 1
         * message : Hello
         */

        private int type;
        private String message;

        public int getType() {
            return type;
        }

        public void setType(int type) {
            this.type = type;
        }

        public String getMessage() {
            return message;
        }

        public void setMessage(String message) {
            this.message = message;
        }
    }
}

**Comment by TCQQ** [comment]
package com.changrui.baseapp.adapter.items;

import android.view.View;
import android.widget.TextView;

import com.changrui.baseapp.R;
import com.changrui.baseapp.model.DataModel;

import java.util.List;

import eu.davidea.flexibleadapter.FlexibleAdapter;
import eu.davidea.flexibleadapter.items.AbstractFlexibleItem;
import eu.davidea.viewholders.FlexibleViewHolder;

public class OneItem extends AbstractFlexibleItem<OneItem.OneHolder> {

    private DataModel.DataBean dataBean;

    public OneItem(DataModel.DataBean dataBean) {
        this.dataBean = dataBean;
    }

    @Override
    public boolean equals(Object o) {
        return false;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_one;
    }

    @Override
    public OneHolder createViewHolder(View view, FlexibleAdapter adapter) {
        return new OneHolder(view, adapter);
    }

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, OneHolder holder, int position, List payloads) {
        holder.mTitle.setText(dataBean.getMessage());
    }

    public static final class OneHolder extends FlexibleViewHolder {

        public TextView mTitle;

        public OneHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter);
            this.mTitle = (TextView) view.findViewById(R.id.tv_one);
        }
    }

}

**Comment by TCQQ** [comment]
Why is the item click event invalid, what am I missing?

**Comment by TCQQ** [comment]
public class TestOneActivity extends BaseActivity implements FlexibleAdapter.OnItemClickListener {

    @BindView(R.id.recycler_view)
    RecyclerView mRecyclerView;

    FlexibleAdapter<AbstractFlexibleItem> mAdapter;

//    List<IFlexible> mList = new ArrayList<>();                          //数据列表
//    FlexibleAdapter<IFlexible> mAdapter = new FlexibleAdapter<>(mList); //适配器

    @Override
    protected int getLayoutId() {
        return R.layout.activity_test_one;
    }

    @Override
    protected void startUi(Bundle savedInstanceState) {
        super.startUi(savedInstanceState);

        String json = "{\n" +
                "    \"data\":[\n" +
                "        {\n" +
                "            \"type\":1,\n" +
                "            \"message\":\"Hello\"\n" +
                "        },\n" +
                "        {\n" +
                "            \"type\":2,\n" +
                "            \"message\":\"World\"\n" +
                "        }\n" +
                "    ]\n" +
                "}";


        DataModel resp = GsonUtils.gsonToModel(json, DataModel.class);

        final List<AbstractFlexibleItem> mItems = new ArrayList<>();

        for (int i = 0; i < resp.getData().size(); i++) {
            mItems.add(new OneItem(resp.getData().get(i)));
        }
        mAdapter.updateDataSet(mItems);


        mAdapter = new FlexibleAdapter<>(new ArrayList<AbstractFlexibleItem>(), this, true);

        mRecyclerView.setLayoutManager(new SmoothScrollLinearLayoutManager(this));
        mRecyclerView.setAdapter(mAdapter);
        mRecyclerView.setHasFixedSize(true);
        mRecyclerView.setNestedScrollingEnabled(false);
        mRecyclerView.setItemAnimator(new DefaultItemAnimator());
    }

    @Override
    public boolean onItemClick(int position) {
        System.out.println(position);
        return false;
    }
}

**Comment by TCQQ** [comment]
public class DataModel {


    private List<DataBean> data;

    public List<DataBean> getData() {
        return data;
    }

    public void setData(List<DataBean> data) {
        this.data = data;
    }

    public static class DataBean {
        /**
         * type : 1
         * message : Hello
         */

        private int type;
        private String message;

        public int getType() {
            return type;
        }

        public void setType(int type) {
            this.type = type;
        }

        public String getMessage() {
            return message;
        }

        public void setMessage(String message) {
            this.message = message;
        }
    }
}

**Comment by TCQQ** [comment]
public class OneItem extends AbstractFlexibleItem<OneItem.OneHolder> {

    private DataModel.DataBean dataBean;

    public OneItem(DataModel.DataBean dataBean) {
        this.dataBean = dataBean;
    }

    @Override
    public boolean equals(Object o) {
        return false;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_one;
    }

    @Override
    public OneHolder createViewHolder(View view, FlexibleAdapter adapter) {
        return new OneHolder(view, adapter);
    }

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, OneHolder holder, int position, List payloads) {
        holder.mTitle.setText(dataBean.getMessage());
    }

    public static final class OneHolder extends FlexibleViewHolder {

        public TextView mTitle;

        public OneHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter);
            this.mTitle = (TextView) view.findViewById(R.id.tv_one);
        }
    }

}

**Comment by TCQQ** [comment]
How to set up dividing line both the sides distance?

<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
       android:shape="rectangle">

	<size
		android:width="1dp"
		android:height="1dp"/>

	<solid android:color="@color/list_choice_pressed_bg_light"/>

</shape>

**Comment by TCQQ** [comment]
If I add a header, it will happen error, what am I doing wrong?

add header code：
mAdapter.addScrollableHeaderWithDelay(new ScrollableUseCaseItem("title", "subtitle"), 1200L, true);

**Comment by TCQQ** [comment]
java.lang.IndexOutOfBoundsException: Index: 18, Size: 18
                                                                     at java.util.ArrayList.get(ArrayList.java:437)
                                                                     at com.changrui.tt.adapter.items.LanguagesItem.bindViewHolder(LanguagesItem.java:53)
                                                                     at com.changrui.tt.adapter.items.LanguagesItem.bindViewHolder(LanguagesItem.java:27)
                                                                     at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1724)
                                                                     at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                                     at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
                                                                     at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
                                                                     at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
                                                                     at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
                                                                     at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
                                                                     at android.os.Handler.handleCallback(Handler.java:789)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by TCQQ** [comment]
public class LanguagesActivity extends BaseActivity implements FlexibleAdapter.OnItemClickListener {

    @BindView(R.id.rv_languages)
    RecyclerView mRecyclerViewLanguages;

    FlexibleAdapter<AbstractFlexibleItem> mAdapter;


    @Override
    protected int getLayoutId() {
        return R.layout.activity_languages;
    }

    @Override
    protected void startUi(Bundle savedInstanceState) {
        super.startUi(savedInstanceState);

        new ToolbarHelper.Builder()
                .setArrowBack(mActivity)
                .setTitle(getString(R.string.activity_language_language) + "(" + LocaleChanger.getLocalesWithDisplayName().size() + ")")
                .setBackgroundColor(ColorUtil.getAppThemeColor())
                .show();

        mAdapter = new FlexibleAdapter<>(new ArrayList<AbstractFlexibleItem>(), this, true);

        mRecyclerViewLanguages.setLayoutManager(new SmoothScrollLinearLayoutManager(this));
        mRecyclerViewLanguages.setAdapter(mAdapter);
        mRecyclerViewLanguages.setHasFixedSize(true); //Size of RV will not change
        mRecyclerViewLanguages.setItemAnimator(new DefaultItemAnimator());

        mAdapter.setDisplayHeadersAtStartUp(true);

        final List<AbstractFlexibleItem> mItems = new ArrayList<>();

        for (int i = 0; i < LocaleChanger.getLocalesWithDisplayName().size(); i++) {
            mItems.add(new LanguagesItem(LocaleChanger.getLocalesWithDisplayName()));
        }

        mAdapter.updateDataSet(mItems);

        mAdapter.addScrollableHeaderWithDelay(new ScrollableUseCaseItem("title", "subtitle"), 1200L, true);
    }

    @Override
    public boolean onItemClick(int position) {
        LocaleChanger.setLocale(LocaleChanger.getLocaleCodeFromIndex(position));
        Intent intent = new Intent(this, MainActivity.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
        startActivity(intent);
        return false;
    }

**Comment by TCQQ** [comment]
public class LanguagesItem extends AbstractFlexibleItem<LanguagesItem.ChildViewHolder> {

    private ArrayList<String> mLanguagesName;

    public LanguagesItem(ArrayList<String> mLanguagesName) {
        this.mLanguagesName = mLanguagesName;
    }

    @Override
    public boolean equals(Object o) {
        return this == o;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_languages;
    }

    @Override
    public LanguagesItem.ChildViewHolder createViewHolder(View view, FlexibleAdapter adapter) {
        AutoUtils.auto(view);
        return new ChildViewHolder(view, adapter);
    }

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, LanguagesItem.ChildViewHolder holder, int position, List payloads) {
        holder.mTextViewLanguages.setText(mLanguagesName.get(position));
        holder.mImageViewSelected.setImageResource(position == LocaleChanger.getIndexFromLocaleCode(Locale.getDefault()) ? R.drawable.ic_radio_button_checked : R.drawable.ic_radio_button_unchecked);
    }

    static final class ChildViewHolder extends FlexibleViewHolder {

        public TextView mTextViewLanguages;
        public ImageView mImageViewSelected;

        public ChildViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter);
            mTextViewLanguages = view.findViewById(R.id.tv_languages);
            mImageViewSelected = view.findViewById(R.id.iv_selected);
        }
    }

**Comment by TCQQ** [comment]
How to set up dividing line both the sides distance?

<size
	android:width="1dp"
	android:height="1dp"/>

<solid android:color="@color/list_choice_pressed_bg_light"/>
    mRecyclerView.addItemDecoration(new FlexibleItemDecoration(getActivity())
            .withDivider(R.drawable.divider, R.layout.recycler_simple_item)
            .withDrawOver(true));
