### ISSUE TITLE
Add scrollable header will be error

### ISSUE THREAD

**Issue by tcqq** [davideas/FlexibleAdapter#588]
When add scrollable header will be error @davideas 
`mAdapter.addScrollableHeader(new LanguagesHeader("H" ,"Hello", "World"));`
What did i do wrong? How should I correct it? Thank you

### LanguagesFragment
```
public class LanguagesFragment extends BaseFragment {

    RecyclerView mRecyclerView;

    SmartAdapter<BaseItem> mAdapter = new SmartAdapter<>(this);

    int mActivatedPosition = -1;


    @Override
    protected int getLayoutId() {
        return R.layout.fragment_languages;
    }

    @Override
    protected void startUi(Bundle state) {
        super.startUi(state);

        final List<Locale> locales = LocaleChanger.getSupportedLocales();

        for (int i = 0; i < locales.size(); i++) {
            final String language = locales.get(i).getLanguage();
            final String country = locales.get(i).getCountry();
            final LanguagesItem item = new LanguagesItem("I" + i, language, country);

            mAdapter.addItem(item);
        }
        mAdapter.setMode(SelectableAdapter.Mode.SINGLE);
        mAdapter.addScrollableHeader(new LanguagesHeader("H" ,"Hello", "World"));

        mRecyclerView = ViewUtil.getRecyclerView(this, R.id.recyclerView);

        final RecyclerView.LayoutManager layoutManager = ViewUtil.newLinearLayoutManager(getContext());
        final DefaultItemAnimator itemAnimator = new DefaultItemAnimator();

        ViewUtil.setRecycler(mRecyclerView, mAdapter, layoutManager, itemAnimator, null);

        final Locale locale = LocaleChanger.getLocale();
        final int index = LocaleChanger.getIndexFromLocale(locale);
        setActivatedPosition(index);
    }

    @Override
    public boolean onItemClick(View view, int position) {
        if (position != mActivatedPosition) {
            setLocale(position);
        }
        return true;
    }

    private void setLocale(int position) {
        setActivatedPosition(position);

        final Locale locale = LocaleChanger.getLocaleFromIndex(position);
        LocaleChanger.setLocale(locale);

        ActivityRecreationHelper.recreate(getParent(), true);
    }

    private void setActivatedPosition(int position) {
        mActivatedPosition = position;
        mAdapter.toggleSelection(position);
    }
}
```
### LanguagesItem
```
public class LanguagesItem extends BaseItem<LanguagesItem.LanguagesViewHolder> {

    private String mLanguage;
    private String mCountry;

    public LanguagesItem(String id, String language, String country) {
        this.id = id;
        this.mLanguage = language;
        this.mCountry = country;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_material_dense_two_line_list_with_icon;
    }

    @Override
    public LanguagesViewHolder createViewHolder(View view, FlexibleAdapter adapter) {
        return new LanguagesViewHolder(view, adapter);
    }

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, LanguagesViewHolder holder, int position, List payloads) {
        final String displayName = new Locale(mLanguage, mCountry).getDisplayName(new Locale(mLanguage, mCountry));
        final String displayLanguage = new Locale(mLanguage, mCountry).getDisplayLanguage();
        final int accentColor = Colorful().getAccentColor().getColorPack().light().asInt();

        holder.mTextViewPrimary.setText(displayName);
        holder.mTextViewSecondary.setText(displayLanguage);
        ViewUtil.setImageResource(holder.mImageViewIcon, R.drawable.ic_check_black_24dp);
        ViewUtil.setImageColor(holder.mImageViewIcon, accentColor);

        if (adapter.isSelected(position)) {
            ViewUtil.visible(holder.mImageViewIcon);
        } else {
            ViewUtil.gone(holder.mImageViewIcon);
        }

        Timber.d("Payloads: %s", payloads);
    }

    @Override
    public boolean filter(Serializable constraint) {
        return false;
    }

    static final class LanguagesViewHolder extends FlexibleViewHolder {

        final AppCompatTextView mTextViewPrimary;
        final AppCompatTextView mTextViewSecondary;
        final AppCompatImageView mImageViewIcon;

        LanguagesViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter);
            mTextViewPrimary = view.findViewById(R.id.primary_text);
            mTextViewSecondary = view.findViewById(R.id.secondary_text);
            mImageViewIcon = view.findViewById(R.id.icon);
        }
    }
}
```
### LanguagesHeader
```
public class LanguagesHeader extends BaseItem<LanguagesHeader.LanguagesViewHolder> {

    private String mLanguage;
    private String mCountry;

    public LanguagesHeader(String id, String language, String country) {
        this.id = id;
        this.mLanguage = language;
        this.mCountry = country;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_material_dense_two_line_list_with_icon;
    }

    @Override
    public LanguagesViewHolder createViewHolder(View view, FlexibleAdapter adapter) {
        return new LanguagesViewHolder(view, adapter);
    }

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, LanguagesViewHolder holder, int position, List payloads) {

        holder.mTextViewPrimary.setText(mLanguage);
        holder.mTextViewSecondary.setText(mCountry);
    }

    @Override
    public boolean filter(Serializable constraint) {
        return false;
    }

    static final class LanguagesViewHolder extends FlexibleViewHolder {

        final AppCompatTextView mTextViewPrimary;
        final AppCompatTextView mTextViewSecondary;
        final AppCompatImageView mImageViewIcon;

        LanguagesViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter);
            mTextViewPrimary = view.findViewById(R.id.primary_text);
            mTextViewSecondary = view.findViewById(R.id.secondary_text);
            mImageViewIcon = view.findViewById(R.id.icon);
        }
    }
}
```
### SmartAdapter
```
public class SmartAdapter<T extends BaseItem> extends BindingFlexibleAdapter<T> {

    private View.OnClickListener clickListener;
    private View.OnLongClickListener longClickListener;

    public SmartAdapter(Object listener) {
        super(listener);
        if (listener instanceof View.OnClickListener) {
            clickListener = (View.OnClickListener) listener;
        }
        if (listener instanceof View.OnLongClickListener) {
            longClickListener = (View.OnLongClickListener) listener;
        }
    }

    public View.OnClickListener getClickListener() {
        return clickListener;
    }

    public View.OnLongClickListener getLongClickListener() {
        return longClickListener;
    }

    @Override
    public boolean addItem(@NonNull T item) {
        if (contains(item)) {
            updateItem(item);
            return true;
        } else {
            return super.addItem(item);
        }
    }

    @Override
    public boolean addItem(int position, @NonNull T item) {
        if (contains(item)) {
            updateItem(item);
            return true;
        } else {
            return super.addItem(position, item);
        }
    }

    public boolean addItem(@NonNull T item, Comparator<IFlexible> comparator) {
        if (contains(item)) {
            updateItem(item);
            return true;
        } else {
            return super.addItem(calculatePositionFor(item, comparator), item);
        }
    }

    @Override
    public void toggleSelection(int position) {
        super.toggleSelection(position);
        notifyItemChanged(position);
    }

    public int getPosition(T item) {
        return getGlobalPositionOf(item);
    }

    public boolean isAnySelected() {
        return getSelectedItemCount() > 0;
    }

    public void addSelection(T item, boolean selected) {
        int position = getGlobalPositionOf(item);
        if (position >= 0) {
            if (selected) {
                addSelection(position);
            } else {
                removeSelection(position);
            }
            notifyItemChanged(position);
        }
    }

    public void selectAll() {
        super.selectAll();
        notifyDataSetChanged();
    }

    @Override
    public void clearSelection() {
        super.clearSelection();
        notifyDataSetChanged();
    }

    public boolean isSelected(T item) {
        return isSelected(getGlobalPositionOf(item));
    }

    public List<T> getSelectedItems() {
        if (getSelectedItemCount() > 0) {
            List<Integer> positions = getSelectedPositions();
            List<T> items = new ArrayList<>(positions.size());
            for (int position : positions) {
                items.add(getItem(position));
            }
            return items;
        }
        return null;
    }
}
```
### BaseItem
```
public abstract class BaseItem<VH extends FlexibleViewHolder> extends AbstractFlexibleItem<VH> implements IFlexible<VH>, IFilterable, Serializable {

    protected String id;
    protected Color color;
    protected int layoutId;
    protected boolean flag;

    protected BaseItem() {
        color = ColorUtil.getRandColor();
    }

    @Override
    public boolean equals(Object inObject) {
        if (inObject instanceof BaseItem && this.id != null) {
            BaseItem item = (BaseItem) inObject;
            return this.id.equals(item.id);
        }
        return false;
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setColor(Color color) {
        this.color = color;
    }

    public void setLayoutId(int layoutId) {
        this.layoutId = layoutId;
    }

    public void setFlag(boolean flag) {
        this.flag = flag;
    }

    public String getId() {
        return id;
    }

    public Color getColor() {
        return color;
    }

    public int getLayoutId() {
        return layoutId;
    }
    public boolean isFlag() {
        return flag;
    }
}
```
## Error Log
`2018-04-09 10:24:13.814 30925-30925/com.changrui.tt E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.changrui.tt, PID: 30925
    java.lang.ClassCastException: com.changrui.tt.data.adapter.items.LanguagesHeader$LanguagesViewHolder cannot be cast to com.changrui.tt.data.adapter.items.LanguagesItem$LanguagesViewHolder
        at com.changrui.tt.data.adapter.items.LanguagesItem.bindViewHolder(LanguagesItem.java:21)
        at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1769)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
        at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:894)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)`

**Comment by davideas** [comment]
@tcqq, the 2 ViewHolders (Item and Header) have same layout Id.

**Comment by tcqq** [comment]
Thank you very much. It is not have error now.  if it allowed Item and Header to use same Layout will be better, I will not need to create an additional identical layout:-)

**Comment by davideas** [comment]
If you need same layout, then you need to override `FlexibleItem.getItemViewType()`.

**Comment by tcqq** [comment]
I checked the sample code, sample used "GridLayoutManage", but I am using "LinearLayoutManager" now. How do I correct it now?

```
    @Override
    protected GridLayoutManager createNewGridLayoutManager() {
        GridLayoutManager gridLayoutManager = new SmoothScrollGridLayoutManager(getActivity(), mColumnCount);
        gridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                // NOTE: If you use simple integers to identify the ViewType,
                // here, you should use them and not Layout integers
                switch (mAdapter.getItemViewType(position)) {
                    case R.layout.recycler_scrollable_expandable_item:
                    case R.layout.recycler_scrollable_header_item:
                    case R.layout.recycler_scrollable_footer_item:
                    case R.layout.recycler_scrollable_layout_item:
                    case R.layout.recycler_scrollable_uls_item:
                    case R.layout.progress_item:
                        return mColumnCount;
                    default:
                        return 1;
                }
            }
        });
        return gridLayoutManager;
    }
```

**Comment by tcqq** [comment]
How should I modify `getItemViewType` is correct?
