### ISSUE TITLE
Feedback sample App IllegalArgumentException Error

### ISSUE THREAD

**Issue by tcqq** [davideas/FlexibleAdapter#591]
```
2018-04-11 18:44:23.429 24328-24328/eu.davidea.samples.flexibleadapter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.davidea.samples.flexibleadapter, PID: 24328
    java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
        at android.support.design.widget.Snackbar.make(Snackbar.java:137)
        at eu.davidea.samples.flexibleadapter.fragments.FragmentSelectionModes$1.run(FragmentSelectionModes.java:98)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

This question may be related to Fragment. [Check out this link](https://stackoverflow.com/questions/21568341/illegalstateexception-fragment-thisfragment-is-not-currently-in-the-fragmentm?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

**Comment by davideas** [comment]
@tcqq, in this case (demoApp) is not so important, since I am not maintaining the old app anymore. Does it occurs when exactly? and happens all the times?

**Comment by tcqq** [comment]
I try to switch multiple windows and switch the activity several times, Switching multiple windows will reset the Activity
