### ISSUE TITLE
cannot be cast in StickyHeaderHelper

### ISSUE THREAD

**Issue by volser** [davideas/FlexibleAdapter#594]
I saw this issue https://github.com/davideas/FlexibleAdapter/issues/299
looks like similar, but marked as resolved.
I use last version 5.0.3

java.lang.ClassCastException: com.test.CategoryTableModelItem$ExpandableHeaderViewHolder cannot be cast to com.test.SubcategoryTableModelItem$ExpandableHeaderViewHolder
	at com.test.SubcategoryTableModelItem.bindViewHolder(SubcategoryTableModelItem.java:32)
	at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1769)
	at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1746)
	at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.updateHeader(StickyHeaderHelper.java:168)
	at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.updateOrClearHeader(StickyHeaderHelper.java:139)
	at eu.davidea.flexibleadapter.FlexibleAdapter$AdapterDataObserver$1.run(FlexibleAdapter.java:5282)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by volser** [comment]
very hard to reproduce (was able 2 times)

**Comment by davideas** [comment]
@volser, I might have an idea. The stacktrace says it comes from an Adapter modification with AdatperDataObserver callback from RV.
The following code has been introduced to give time to the LayoutManager to finish the layout and so having the positions synced.
``` java
// #320 - To include adapter changes just notified we need a new layout pass:
// We must give time to LayoutManager otherwise ... will return wrong position!
mRecyclerView.postDelayed(new Runnable() {
    @Override
    public void run() {
        if (areHeadersSticky()) mStickyHeaderHelper.updateOrClearHeader(true);
    }
}, 50L);
```
That 50ms might be too low, it might explain why it's hard to reproduce.
I can try to build a SNAPSHOT version increasing that value, so you can try and tell me.
I can eventually check if the object is of the same type and allow the binding.

**Comment by davideas** [comment]
Please try with 5.0.4-SNAPSHOT, this has 100ms delay.
I've also put an if-else when itemView types don't match, you should see an error log with the Holders class names (I expect to be different in that case).
```
allprojects {
    repositories {
        // For SNAPSHOT
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
}
```
```
dependencies {
    implementation ('eu.davidea:flexible-adapter:5.0.4-SNAPSHOT') {
        changing = true;
    }
}
```

**Comment by davideas** [comment]
@volser waiting your tests. Thanks :-)

**Comment by volser** [comment]
@davideas thank you! I will test soon, but it will take some time, cuz it's not so easy to reproduce )
