### ISSUE TITLE
Do you have any plan to support FlexboxLayoutManager?

### ISSUE THREAD

**Issue by longht89** [davideas/FlexibleAdapter#596]
Do you have any plan to support FlexboxLayoutManager?

At the moment, It's always crash.

`04-18 10:01:58.802 2288-2288/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.examples.myapplication, PID: 2288
    java.lang.ClassCastException: com.google.android.flexbox.FlexboxLayoutManager cannot be cast to android.support.v7.widget.LinearLayoutManager
        at eu.davidea.flexibleadapter.common.FlexibleLayoutManager.findLastVisibleItemPosition(FlexibleLayoutManager.java:188)
        at eu.davidea.flexibleadapter.AnimatorAdapter.animateView(AnimatorAdapter.java:320)
        at eu.davidea.flexibleadapter.FlexibleAdapter.onBindViewHolder(FlexibleAdapter.java:1782)`

I'd like to use Flexbox to implement some special ui, but it's not work.

Thanks in advance!

**Comment by davideas** [comment]
It's already supported: any third class are supported even for the ones created in the future.
Just need to implement the interface. Check the closed issues.
