### ISSUE TITLE
onRestoreInstanceState observation

### ISSUE THREAD

**Issue by hoordev** [davideas/FlexibleAdapter#611]
Current date: 2018-05-18 10:20:38 
    Device: Samsung SM-G965F 
     
    Stack trace:  
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Collection.size()' on a null object reference
        at java.util.TreeSet.addAll(TreeSet.java:300)
        at java.util.Collections$SynchronizedCollection.addAll(Collections.java:2089)
        at eu.davidea.flexibleadapter.SelectableAdapter.onRestoreInstanceState(SelectableAdapter.java:577)
        at eu.davidea.flexibleadapter.FlexibleAdapter.onRestoreInstanceState(FlexibleAdapter.java:5072)
        at xx.xx.yyy.xxvvvxxxx.xxx.DummyFragment.onCreateView(DummyFragment.java:103)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:792)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager$3.run(ViewPager.java:267)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Maybe is this adapter responsibility ?

But there are 2 flexible adapter on this page.

Thanks!

**Comment by davideas** [comment]
@hoordev, depends by the logic you have here: `DummyFragment.onCreateView(DummyFragment.java:103)`:

Currently I'm not checking that `savedInstanceState.getIntegerArrayList(TAG)` is null, but possibly I can do it. However, it still doesn't restore anything so it's useless to call this function! It returns `null` because you shouldn't call it in all cases but only when `savedInstanceState` is not `null` and of course you saved the adapter state previously, so the list exists.

**Comment by davideas** [comment]
Regarding the TAG value, indeed I have only 1, so it might restore the selection of the other adapter, I need to check it.

**Comment by hoordev** [comment]
I wrote simple code and succes to reporuduce error.

`    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.xy_fragment, container, false);

        if (savedInstanceState != null) {
            if (xx!= null) {
                xx.onRestoreInstanceState(savedInstanceState);
            }
            if (yy!= null) {
                yy.onRestoreInstanceState(savedInstanceState);
            }
        }

        return super.onCreateView(inflater, container, savedInstanceState);
    }
`
and code is on saved state
`    @Override
    public void onSaveInstanceState(@NonNull Bundle outState) {
        if (xx!= null) {
            xx.onSaveInstanceState(outState);
        }
        if (yy!= null) {
            yy.onSaveInstanceState(outState);
        }
        super.onSaveInstanceState(outState);
    }`

**Comment by davideas** [comment]
@hoordev. I see, that condition should be ok, but don't you have a fragment with its adapter inside?
In demoApp I have one Adapter encapsulated in each `FragmentViewPager` instance.

**Comment by davideas** [comment]
@hoordev, do you have 2 Adapters in the same Fragment for 2 RecyclerViews layouts?
Can you DEBUG(!) and check the content of the savedStateInstance? how many variables and of what type are in there?

**Comment by davideas** [comment]
If you don't have any update, I will close this issue.

**Comment by hoordev** [comment]
Thanks. Are now everything good. No more questions (y)
