### ISSUE TITLE
[BUG] Demo App: Data Binding fragment - Crash

### ISSUE THREAD

**Issue by Mavbraz** [davideas/FlexibleAdapter#626]
# Info
- Demo App version: 5.0.5
- Android version: 6.0.1
- Fragment: Data Binding

# Steps to reproduce
1. Open the demo app
2. Go to "Data Binding" fragment
3. Check if "No items" is visible
4. Then, scroll up three times
5. Click on FAB button

# Results after reproduce
- The app will crash

# Log
```
07-02 19:48:28.154: E/AndroidRuntime(28290): FATAL EXCEPTION: main
07-02 19:48:28.154: E/AndroidRuntime(28290): Process: eu.davidea.samples.flexibleadapter, PID: 28290
07-02 19:48:28.154: E/AndroidRuntime(28290): java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{83ed613 position=12 id=2702, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{a532e9b VFED..... .F...... 0,0-720,1120 #7f0900c4 app:id/recycler_view}, adapter:eu.davidea.flexibleadapter.databinding.BindingFlexibleAdapter@cb13d80, layout:eu.davidea.flexibleadapter.common.SmoothScrollLinearLayoutManager@9345fb9, context:android.view.ContextThemeWrapper@28d4ffe
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5610)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5792)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3763)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3527)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1767)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4928)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.view.Choreographer.doFrame(Choreographer.java:619)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.os.Handler.handleCallback(Handler.java:739)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.os.Looper.loop(Looper.java:148)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at android.app.ActivityThread.main(ActivityThread.java:7325)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at java.lang.reflect.Method.invoke(Native Method)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
07-02 19:48:28.154: E/AndroidRuntime(28290): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by davideas** [comment]
I have no idea.

**Comment by evgenybozhko2** [comment]
It happens if you call .postValue() for mutableLiveData from coroutines different scopes. For example from Dispatchers.IO and Main.
