### ISSUE TITLE
FlexibleAdapter onCreateViewHolder is throwing exception

### ISSUE THREAD

**Issue by kriishna** [davideas/FlexibleAdapter#641]
1) For Bugs / Support
When i extended FlexibleAdapter<AbstractFlexibleItem> , i am facing issue..
**### item.createViewHolder(mInflater.inflate(item.getLayoutRes(), parent, false), this);** on this line..

 **android.view.InflateException: Binary XML file line #50: Binary XML file line #50: Error inflating class TextView
    Caused by: android.view.InflateException: Binary XML file line #50: Error inflating class TextView**
    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f040156 a=-1}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:562)
        at android.widget.TextView.<init>(TextView.java:1137)
        at android.widget.TextView.<init>(TextView.java:746)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:76)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:72)
        at android.support.v7.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:176)
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:101)
        at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1035)
        at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1092)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       ###  **at eu.davidea.flexibleadapter.FlexibleAdapter.onCreateViewHolder(FlexibleAdapter.java:1742)**
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:17702)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17702)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
        at android.view.View.layout(View.java:17702)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17702)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17702)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1858)
        at android.view.View.layout(View.java:17702)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17702)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
        at android.view.View.layout(View.java:17702)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17702)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1762)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1606)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1515)
        at android.view.View.layout(View.java:17702)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:774)
        at android.view.View.layout(View.java:17702)
        at android.view.ViewGroup.layout(ViewGroup.java:5631)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2519)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2234)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1372)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6774)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
        at android.view.Choreographer.doCallbacks(Choreographer.java:735)
        at android.view.Choreographer.doFrame(Choreographer.java:667)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by davideas** [comment]
Sorry @kriishna. Check your layout.
