### ISSUE TITLE
Expand an item and push the current fragment

### ISSUE THREAD

**Issue by lv15** [davideas/FlexibleAdapter#646]
When you have pressed over an item and the same time expand the view and navigate to another fragment, the system show the next error:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.widget.RecyclerView$LayoutManager android.support.v7.widget.RecyclerView.getLayoutManager()' on a null object reference
       at eu.davidea.flexibleadapter.SelectableAdapter.getFlexibleLayoutManager(SelectableAdapter.java:200)
       at eu.davidea.flexibleadapter.FlexibleAdapter$13.handleMessage(FlexibleAdapter.java:4719)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6914)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by davideas** [comment]
@lv15, why RecyclerView (RV) should become null, then? Also, if you don't use a third party layout manager, you can get it directly from RV a not through the Adapter. The null pointer is because RV is null, so you can't call that method in that condition.
However, can you explain why you do 2 UI operations at once? expand and navigate to another Fragment? do they remain visible simultaneously or Fragment hides RV?
