### ISSUE TITLE
ClassCastException at FlexibleAdapter.onViewRecycled

### ISSUE THREAD

**Issue by ch4ndu** [davideas/FlexibleAdapter#650]
Approximate steps to reproduce this...
1. Show sticky headers
2. Filter items
3. Scroll to the bottom of the list
4. Clear the filter

v5.0.5 btw..

This doesn't happen in every list(album) in my app as well...just a few ones.

08-15 23:17:13.438 2257-2257/com.udnahc.puregallery.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.udnahc.puregallery.debug, PID: 2257
    java.lang.ClassCastException: udnahc.com.puregallery.album.GroupPhotoHeader$HeaderViewHolder cannot be cast to udnahc.com.puregallery.album.MediaItem$PhotoViewHolder
        at udnahc.com.puregallery.album.MediaItem.unbindViewHolder(MediaItem.java:48)
        at eu.davidea.flexibleadapter.FlexibleAdapter.onViewRecycled(FlexibleAdapter.java:1825)
        at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.swapHeader(StickyHeaderHelper.java:245)
        at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.updateHeader(StickyHeaderHelper.java:162)
        at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.updateOrClearHeader(StickyHeaderHelper.java:138)
        at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.onScrolled(StickyHeaderHelper.java:64)
        at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4844)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3909)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3540)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)

**Comment by davideas** [comment]
@ch4ndu, check the viewType/layoutId and the equals methods implementation of the items.
