### ISSUE TITLE
AndroidX: Error inflating class

### ISSUE THREAD

**Issue by Quarx2k** [davideas/FlexibleAdapter#677]
Hello. Have a problem on some android devices(samusng and asus) with  5.0.2 and 7.0  + AndroidX.
I can't reproduce it myself, but many crashes in Fabric.
Thanks.

**Libs:**
implementation 'eu.davidea:flexible-adapter:5.1.0'
implementation 'eu.davidea:flexible-adapter-ui:1.0.0'

**Gradle settings:**
android.useAndroidX=true
android.enableJetifier=true

**StackTrace:**
Fatal Exception: android.view.InflateException: Binary XML file line #64: Error inflating class android.support.v7.widget.RecyclerView
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at com.mikepenz.iconics.context.InternalLayoutInflater.inflate(InternalLayoutInflater.java:81)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at eu.davidea.flexibleadapter.FlexibleAdapter.onCreateViewHolder(FlexibleAdapter.java:1733)
       at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
       at android.view.View.layout(View.java:15612)

**Comment by Quarx2k** [comment]
Oops, sorry. I found problem in my XML :)
Thank you, rubber duck! 👍
