### ISSUE TITLE
[BUG] Demo App: Crash on the very start of the app.

### ISSUE THREAD

**Issue by Ashanen** [davideas/FlexibleAdapter#704]
App crashes on Nokia 7.1 android 9.0, but also on an emulator. 
Steps to reproduce -> instal app -> Open -> Crash 

`2019-01-09 10:46:07.983 17136-17145/? E/davidea.blueap: Failed to send DDMS packet REAQ to debugger (-1 of 20): Broken pipe
2019-01-09 10:46:11.154 17136-17136/eu.davidea.blueapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.davidea.blueapp, PID: 17136
    java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.davidea.blueapp/eu.davidea.blueapp.ui.MainActivity}: java.lang.IllegalArgumentException: URL "/v1/threads/{threadId}" does not contain "{userId}". (parameter #2)
        for method MessageApi.getConversation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: URL "/v1/threads/{threadId}" does not contain "{userId}". (parameter #2)
        for method MessageApi.getConversation
        at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:752)
        at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:743)
        at retrofit2.ServiceMethod$Builder.parameterError(ServiceMethod.java:761)
        at retrofit2.ServiceMethod$Builder.validatePathName(ServiceMethod.java:729)
        at retrofit2.ServiceMethod$Builder.parseParameterAnnotation(ServiceMethod.java:399)
        at retrofit2.ServiceMethod$Builder.parseParameter(ServiceMethod.java:336)
        at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:204)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy1.getConversation(Unknown Source)
        at eu.davidea.blueapp.persistence.repositories.MessageRepository.loadConversation(MessageRepository.java:41)
        at eu.davidea.blueapp.viewmodels.message.MessageViewModel.loadConversation(MessageViewModel.java:155)
        at eu.davidea.blueapp.ui.MainActivity.onCreate(MainActivity.java:101)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        	... 11 more`

**Comment by pablichjenkov** [comment]
It does not seem related to the library. Apparently you need to specify a userId for your api request.

**Comment by davideas** [comment]
Sorry @Ashanen, blueapp isn't a project finalized as this library.
Indeed, the error is not related to this Adapter.
