### ISSUE TITLE
Using FlexibleAdapter in Timeline-View has problem

### ISSUE THREAD

**Issue by tcqq** [davideas/FlexibleAdapter#713]
@davideas I want to use FlexibleAdapter in [Timeline-View](https://github.com/vipulasri/Timeline-View)

This is the correct effect(Not using FlexibleAdapter): ![tim 20190212123335](https://user-images.githubusercontent.com/10644057/52612051-15c14980-2ec3-11e9-8efa-8c6c698a20a0.png)

This is the effect now(Using FlexibleAdapter): ![tim 20190212124307](https://user-images.githubusercontent.com/10644057/52612286-fe369080-2ec3-11e9-9a87-25c6b4f4b211.png)

Because I am not configuring this code in the adapter now:
```
    @Override
    public int getItemViewType(int position) {
        return TimelineView.getTimeLineViewType(position, getItemCount());
    }
```
So causes the timeline to display extra errors lines in the first and last items.

I tried to create the adapter and added the `getItemViewType` method:

```
class MilestoneDashboardAdapter(items: List<AbstractFlexibleItem<*>>, listeners: Any) : FlexibleAdapter<AbstractFlexibleItem<*>>(items, listeners, true) {

    override fun getItemViewType(position: Int): Int {
        return TimelineView.getTimeLineViewType(position, itemCount)
    }
}
```

But a #555 error has occurred:

```
    java.lang.IllegalStateException: ViewType instance not found for viewType 1. You should implement the AutoMap properly.
        at eu.davidea.flexibleadapter.FlexibleAdapter.onCreateViewHolder(FlexibleAdapter.java:1728)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6942)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6114)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5997)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5993)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2227)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:613)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4029)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3441)
```

This example can reproduce the above problem: https://github.com/tcqq/TimelineExample

I want to use FlexibleAdapter in Timeline-View, how should I fix it? Thank you.

**Comment by tcqq** [comment]
I found a way to use it in the FlexibleAdapter, just add the following code.

```
    override fun bindViewHolder(adapter: FlexibleAdapter<IFlexible<RecyclerView.ViewHolder>>, holder: ViewHolder, position: Int, payloads: MutableList<Any>) {
        holder.timeline.initLine(holder.timeline.getTimeLineViewType(position, adapter.itemCount))
    }
```
