### ISSUE TITLE
Classcast Exception

### ISSUE THREAD

**Issue by vdotm** [davideas/FlexibleAdapter#737]
I am using eu.davidea:flexible-adapter:5.1.0' to show expandable list view headers in recyclerview. However, there is a case, where I would like to disable sticky headers. 
So in view holder class, that extends from ExpandableViewHolder. I am setting the stickyHeader to false using this constructor   super(view, adapter, false);//True for sticky

When the recycler view item is updated, I get the following exception

java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to androidx.recyclerview.widget.RecyclerView$LayoutParams
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.getLeftDecorationWidth(RecyclerView.java:9492)
        at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.applyLayoutParamsAndMargins(StickyHeaderHelper.java:275)
        at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.ensureHeaderParent(StickyHeaderHelper.java:262)
        at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.updateHeader(StickyHeaderHelper.java:173)
        at eu.davidea.flexibleadapter.helpers.StickyHeaderHelper.updateOrClearHeader(StickyHeaderHelper.java:138)
        at eu.davidea.flexibleadapter.FlexibleAdapter$AdapterDataObserver$1.run(FlexibleAdapter.java:5336)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)

What am I missing ? Can you please help?

**Comment by davideas** [comment]
@vdotm, You must keep that constructor with `true` if you have element with sticky headers in your project.  To disable sticky headers you must use the Adapter function.

**Comment by vdotm** [comment]
Thanks a lot for the quick reply. I was able to set it through the adapter function.
