### ISSUE TITLE
Position is inconsistent for the header 

### ISSUE THREAD

**Issue by EpariNigam** [davideas/FlexibleAdapter#81]
I found another issue, the position is inconsistent for the header view holder.

The method `getFlexibleAdapterPosition()` returns -1 sometimes for the header click events also the getAdapterPosition() returns -1 

For reference inside `HeaderItem.HeaderViewHolder` in the onClick() event.

**Comment by davideas** [comment]
same question, before or after the modification?

**Comment by EpariNigam** [comment]
Its already there before modification. The issue is coming sometimes.

**Comment by davideas** [comment]
This should not happen because at the moment the item is sticky the position is known and manually set in the holder, that's why I crated `getFlexibleAdapterPosition()`. Unfortunately `getAdapterPosition()` cannot be used due to the fact while scrolling the item might be scrapped and so the position of the sticky item is unknown.
I cannot reproduce that `getFlexibleAdapterPosition()` returns -1, I don't know how you got that.

**Comment by EpariNigam** [comment]
But, it happened to me. I doesn't know why?

**Comment by yilzer** [comment]
`  Process: com.reactionmemes, PID: 30489
                                                                   java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{9a846b6 position=30 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}
                                                                       at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4505)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4636)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                                       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:528)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                       at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:2979)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2904)
                                                                       at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1482)
                                                                       at android.support.v7.widget.RecyclerView.access$400(RecyclerView.java:147)
                                                                       at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:294)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)`


When i fill the adapter it works perfect, but when i finish the activity or call onbackpressed() this error shows up every time. The id is also -1, so i thought maybe is this the same bug.
