### ISSUE TITLE
The specified child already has  a parent.

### ISSUE THREAD

**Issue by EpariNigam** [davideas/FlexibleAdapter#82]
I faced another new issue, in the normal Sticky Header.

`Process: eu.davidea.examples.flexibleadapter, PID: 3172
                                                                                   java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                                       at android.view.ViewGroup.addViewInner(ViewGroup.java:3936)
                                                                                       at android.view.ViewGroup.addView(ViewGroup.java:3786)
                                                                                       at android.view.ViewGroup.addView(ViewGroup.java:3727)
                                                                                       at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:611)
                                                                                       at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
                                                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:6728)
                                                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6686)
                                                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:6674)
                                                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1404)
                                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                                       at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1180)
                                                                                       at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1031)
                                                                                       at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4061)
                                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                       at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Comment by davideas** [comment]
This is before or after the modification? It should be after.

**Comment by EpariNigam** [comment]
@davideas 
Yes, I also think that, its after modification in the code. Because, previously I didn't faced this type of issue.

**Comment by EpariNigam** [comment]
@davideas 
Why you closed the issue.

**Comment by davideas** [comment]
This and the other you just opened are not important, because it is related to the fix, not part of library published or it's related to the main issue.
The main issue remains the ClassCastException on LayoutParams, so please write there.

**Comment by CTKnight** [comment]
I also encountered this issue. It happens when program call `updateDataset(list)` and scrolling the `RecyclerView` at the same time.
```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                       at android.view.ViewGroup.addViewInner(ViewGroup.java:4309)
                                                                       at android.view.ViewGroup.addView(ViewGroup.java:4145)
                                                                       at android.view.ViewGroup.addView(ViewGroup.java:4086)
                                                                       at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:638)
                                                                       at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
                                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7054)
                                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7012)
                                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1430)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                       at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1193)
                                                                       at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1043)
                                                                       at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1552)
                                                                       at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2649)
                                                                       at android.view.View.dispatchTouchEvent(View.java:9301)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2659)
                                                                       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1787)
                                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
                                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
                                                                       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2620)
                                                                       at android.view.View.dispatchPointerEvent(View.java:9521)
                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
                                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
```

**Comment by stepansanda** [comment]
This issue is still there. Why is this closed? How did you solve it?

> E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                         Process: com.test.android.dev, PID: 23835
>                                                                         java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
>                                                                             at android.view.ViewGroup.addViewInner(ViewGroup.java:4417)
>                                                                             at android.view.ViewGroup.addView(ViewGroup.java:4258)
>                                                                             at android.view.ViewGroup.addView(ViewGroup.java:4198)
>                                                                             at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:711)
>                                                                             at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
>                                                                             at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7877)
>                                                                             at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7835)
>                                                                             at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7823)
>                                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1565)
>                                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
>                                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
>                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
>                                                                             at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
>                                                                             at android.view.View.measure(View.java:19857)
>                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
>                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
>                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
>                                                                             at android.view.View.measure(View.java:19857)
>                                                                             at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1293)
>                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                                             at android.widget.ScrollView.onMeasure(ScrollView.java:340)
>                                                                             at android.view.View.measure(View.java:19857)
>                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                                             at android.view.View.measure(View.java:19857)
>                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                                             at android.view.View.measure(View.java:19857)
>                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                             at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
>                                                                             at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
>                                                                             at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1391)
>                                                                             at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
>                                                                             at android.view.View.measure(View.java:19857)
>                                                                             at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1081)
>                                                                             at android.view.View.measure(View.java:19857)
>                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                                             at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
>                                                                             at android.view.View.measure(View.java:19857)
>                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
>                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
>                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
>                                                                             at android.view.View.measure(View.java:19857)
>                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                                             at android.view.View.measure(View.java:19857)
>                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
>                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
>                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
>                                                                             at android.view.View.measure(View.java:19857)
> 05-18 14:20:21.021 23835-23835/com.test.android.dev E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                                             at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
>                                                                             at android.view.View.measure(View.java:19857)
>                                                                             at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
>                                                                             at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
>                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
>                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
>                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
>                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
>                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:686)
>                                                                             at android.view.Choreographer.doFrame(Choreographer.java:621)
>                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
>                                                                             at android.os.Handler.handleCallback(Handler.java:751)
>                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                             at android.os.Looper.loop(Looper.java:154)
>                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
>                                                                             at java.lang.reflect.Method.invoke(Native Method)
>                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by davideas** [comment]
@stepansanda, in which version you get that exception?

**Comment by stepansanda** [comment]
@davideas It is happening when I call `updateDataSet(..)` on adapter its `recyclerview` is inside `scrollview`. When I call `clear() `and then `addItems(..)` it works correctly.

**Comment by davideas** [comment]
Uhm, can you please provide me the logs of the adapter? It might be there something that could help me to analyse the issue.

**Comment by dev-JE02** [comment]
Hi I am also encountering this issue. It is happening when I repeatedly refresh the list with items multiple times.

```
9-02 00:06:34.771 10783-10783/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: [package], PID: 10783
                                                   java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                       at android.view.ViewGroup.addViewInner(ViewGroup.java:4496)
                                                       at android.view.ViewGroup.addView(ViewGroup.java:4337)
                                                       at android.view.ViewGroup.addView(ViewGroup.java:4277)
                                                       at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:711)
                                                       at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7877)
                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7835)
                                                       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7823)
                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1565)
                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
                                                       at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1637)
                                                       at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:343)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:616)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6247)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by davideas** [comment]
I do not know if this is caused by the sticky header helper. However now, I've put a try catch when setting parent on header swapping. But, it could be also the opposite: The RV wants its child back while the child is "busy" in the header container layout.
It seems it occurs when LayoutManager is busy with something and a change of the items arrives, all in few _milliseconds_.

**Comment by dev-JE02** [comment]
Yes I actually use sticky headers on all of my lists
