### ISSUE TITLE
[5.0.0-b6 & May 29th Snapshot] Crash after top sticky header collapse->expand->collapse

### ISSUE THREAD

**Issue by bornest** [davideas/FlexibleAdapter#92]
Hi! The lib is great, but I've found a bug in it.

I use expandable sections and sticky headers similar to "Expandable Sections" in example app.

All sections are expanded at startup.
Collapse the topmost section, then expand it.
Then, when you collapse it again, the app crashes with fatal exception.

both 5.0.0-b6 and May 29th SNAPSHOT have this bug.

BTW Found the same exact bug in "Expandable Sections" in the latest Example App from this repo (cloned the latest version of this repo). 

`FATAL EXCEPTION: main
                                                                                    Process: , PID: 12203
                                                                                    java.lang.RuntimeException: trying to unhide a view that was not hiddenandroid.widget.LinearLayout{1e27b719 V.E...CL ........ 0,1627-1080,2155}
                                                                                        at android.support.v7.widget.ChildHelper.unhide(ChildHelper.java:355)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.getScrapViewForPosition(RecyclerView.java:5080)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4634)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                                        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                                                        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                                                                                        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                                        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:592)
                                                                                        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:2979)
                                                                                        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2904)
                                                                                        at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1482)
                                                                                        at android.support.v7.widget.RecyclerView.access$400(RecyclerView.java:147)
                                                                                        at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:294)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                                        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)`

**Comment by davideas** [comment]
@bornest, thanks for spotting this, I confirm it, but I also confirm that, it is related to the technique used for the sticky header, so it is part of the same bugs #78 and #79 already opened few weeks ago.

**Comment by davideas** [comment]
@bornest, please follow the discussion in issue 79. I have some good news.
